// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.provisions;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.audio.AudioDeviceModule;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LKObjects_Factory implements Factory<LKObjects> {
  private final Provider<EglBase> eglBaseProvider;

  private final Provider<AudioDeviceModule> audioDeviceModuleProvider;

  public LKObjects_Factory(Provider<EglBase> eglBaseProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider) {
    this.eglBaseProvider = eglBaseProvider;
    this.audioDeviceModuleProvider = audioDeviceModuleProvider;
  }

  @Override
  public LKObjects get() {
    return newInstance(eglBaseProvider, audioDeviceModuleProvider);
  }

  public static LKObjects_Factory create(Provider<EglBase> eglBaseProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider) {
    return new LKObjects_Factory(eglBaseProvider, audioDeviceModuleProvider);
  }

  public static LKObjects newInstance(Provider<EglBase> eglBaseProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider) {
    return new LKObjects(eglBaseProvider, audioDeviceModuleProvider);
  }
}
