// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.datastream.incoming;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class IncomingDataStreamManagerImpl_Factory implements Factory<IncomingDataStreamManagerImpl> {
  @Override
  public IncomingDataStreamManagerImpl get() {
    return newInstance();
  }

  public static IncomingDataStreamManagerImpl_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static IncomingDataStreamManagerImpl newInstance() {
    return new IncomingDataStreamManagerImpl();
  }

  private static final class InstanceHolder {
    private static final IncomingDataStreamManagerImpl_Factory INSTANCE = new IncomingDataStreamManagerImpl_Factory();
  }
}
