// Generated by Dagger (https://dagger.dev).
package io.livekit.android.audio;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AudioSwitchHandler_Factory implements Factory<AudioSwitchHandler> {
  private final Provider<Context> contextProvider;

  public AudioSwitchHandler_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public AudioSwitchHandler get() {
    return newInstance(contextProvider.get());
  }

  public static AudioSwitchHandler_Factory create(Provider<Context> contextProvider) {
    return new AudioSwitchHandler_Factory(contextProvider);
  }

  public static AudioSwitchHandler newInstance(Context context) {
    return new AudioSwitchHandler(context);
  }
}
