// Generated by Dagger (https://dagger.dev).
package io.livekit.android.audio;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class CommunicationWorkaroundImpl_Factory implements Factory<CommunicationWorkaroundImpl> {
  private final Provider<Context> contextProvider;

  private final Provider<CoroutineDispatcher> dispatcherProvider;

  public CommunicationWorkaroundImpl_Factory(Provider<Context> contextProvider,
      Provider<CoroutineDispatcher> dispatcherProvider) {
    this.contextProvider = contextProvider;
    this.dispatcherProvider = dispatcherProvider;
  }

  @Override
  public CommunicationWorkaroundImpl get() {
    return newInstance(contextProvider.get(), dispatcherProvider.get());
  }

  public static CommunicationWorkaroundImpl_Factory create(Provider<Context> contextProvider,
      Provider<CoroutineDispatcher> dispatcherProvider) {
    return new CommunicationWorkaroundImpl_Factory(contextProvider, dispatcherProvider);
  }

  public static CommunicationWorkaroundImpl newInstance(Context context,
      CoroutineDispatcher dispatcher) {
    return new CommunicationWorkaroundImpl(context, dispatcher);
  }
}
