// Generated by Dagger (https://dagger.dev).
package io.livekit.android.audio;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class NoAudioHandler_Factory implements Factory<NoAudioHandler> {
  @Override
  public NoAudioHandler get() {
    return newInstance();
  }

  public static NoAudioHandler_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static NoAudioHandler newInstance() {
    return new NoAudioHandler();
  }

  private static final class InstanceHolder {
    private static final NoAudioHandler_Factory INSTANCE = new NoAudioHandler_Factory();
  }
}
