// Generated by Dagger (https://dagger.dev).
package io.livekit.android.audio;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class NoopCommunicationWorkaround_Factory implements Factory<NoopCommunicationWorkaround> {
  @Override
  public NoopCommunicationWorkaround get() {
    return newInstance();
  }

  public static NoopCommunicationWorkaround_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static NoopCommunicationWorkaround newInstance() {
    return new NoopCommunicationWorkaround();
  }

  private static final class InstanceHolder {
    private static final NoopCommunicationWorkaround_Factory INSTANCE = new NoopCommunicationWorkaround_Factory();
  }
}
