// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class DefaultsManager_Factory implements Factory<DefaultsManager> {
  @Override
  public DefaultsManager get() {
    return newInstance();
  }

  public static DefaultsManager_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static DefaultsManager newInstance() {
    return new DefaultsManager();
  }

  private static final class InstanceHolder {
    private static final DefaultsManager_Factory INSTANCE = new DefaultsManager_Factory();
  }
}
