// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import android.javax.sdp.SdpFactory;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;
import livekit.org.webrtc.PeerConnection;
import livekit.org.webrtc.PeerConnectionFactory;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class PeerConnectionTransport_Factory {
  private final Provider<CoroutineDispatcher> ioDispatcherProvider;

  private final Provider<PeerConnectionFactory> connectionFactoryProvider;

  private final Provider<SdpFactory> sdpFactoryProvider;

  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  public PeerConnectionTransport_Factory(Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<PeerConnectionFactory> connectionFactoryProvider,
      Provider<SdpFactory> sdpFactoryProvider, Provider<RTCThreadToken> rtcThreadTokenProvider) {
    this.ioDispatcherProvider = ioDispatcherProvider;
    this.connectionFactoryProvider = connectionFactoryProvider;
    this.sdpFactoryProvider = sdpFactoryProvider;
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
  }

  public PeerConnectionTransport get(PeerConnection.RTCConfiguration config,
      PeerConnection.Observer pcObserver, PeerConnectionTransport.Listener listener) {
    return newInstance(config, pcObserver, listener, ioDispatcherProvider.get(), connectionFactoryProvider.get(), sdpFactoryProvider.get(), rtcThreadTokenProvider.get());
  }

  public static PeerConnectionTransport_Factory create(
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<PeerConnectionFactory> connectionFactoryProvider,
      Provider<SdpFactory> sdpFactoryProvider, Provider<RTCThreadToken> rtcThreadTokenProvider) {
    return new PeerConnectionTransport_Factory(ioDispatcherProvider, connectionFactoryProvider, sdpFactoryProvider, rtcThreadTokenProvider);
  }

  public static PeerConnectionTransport newInstance(PeerConnection.RTCConfiguration config,
      PeerConnection.Observer pcObserver, PeerConnectionTransport.Listener listener,
      CoroutineDispatcher ioDispatcher, PeerConnectionFactory connectionFactory,
      SdpFactory sdpFactory, RTCThreadToken rtcThreadToken) {
    return new PeerConnectionTransport(config, pcObserver, listener, ioDispatcher, connectionFactory, sdpFactory, rtcThreadToken);
  }
}
