// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;
import livekit.org.webrtc.PeerConnection;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class PeerConnectionTransport_Factory_Impl implements PeerConnectionTransport.Factory {
  private final PeerConnectionTransport_Factory delegateFactory;

  PeerConnectionTransport_Factory_Impl(PeerConnectionTransport_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public PeerConnectionTransport create(PeerConnection.RTCConfiguration config,
      PeerConnection.Observer pcObserver, PeerConnectionTransport.Listener listener) {
    return delegateFactory.get(config, pcObserver, listener);
  }

  public static Provider<PeerConnectionTransport.Factory> create(
      PeerConnectionTransport_Factory delegateFactory) {
    return InstanceFactory.create(new PeerConnectionTransport_Factory_Impl(delegateFactory));
  }
}
