// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import java.net.URI;
import javax.inject.Provider;
import kotlinx.serialization.json.Json;
import okhttp3.OkHttpClient;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RegionUrlProvider_Factory {
  private final Provider<OkHttpClient> okHttpClientProvider;

  private final Provider<Json> jsonProvider;

  public RegionUrlProvider_Factory(Provider<OkHttpClient> okHttpClientProvider,
      Provider<Json> jsonProvider) {
    this.okHttpClientProvider = okHttpClientProvider;
    this.jsonProvider = jsonProvider;
  }

  public RegionUrlProvider get(URI serverUrl, String token) {
    return newInstance(serverUrl, token, okHttpClientProvider.get(), jsonProvider.get());
  }

  public static RegionUrlProvider_Factory create(Provider<OkHttpClient> okHttpClientProvider,
      Provider<Json> jsonProvider) {
    return new RegionUrlProvider_Factory(okHttpClientProvider, jsonProvider);
  }

  public static RegionUrlProvider newInstance(URI serverUrl, String token,
      OkHttpClient okHttpClient, Json json) {
    return new RegionUrlProvider(serverUrl, token, okHttpClient, json);
  }
}
