// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import java.net.URI;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RegionUrlProvider_Factory_Impl implements RegionUrlProvider.Factory {
  private final RegionUrlProvider_Factory delegateFactory;

  RegionUrlProvider_Factory_Impl(RegionUrlProvider_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public RegionUrlProvider create(URI serverUrl, String token) {
    return delegateFactory.get(serverUrl, token);
  }

  public static Provider<RegionUrlProvider.Factory> create(
      RegionUrlProvider_Factory delegateFactory) {
    return InstanceFactory.create(new RegionUrlProvider_Factory_Impl(delegateFactory));
  }
}
