// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import android.content.Context;
import android.net.ConnectivityManager;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioHandler;
import io.livekit.android.audio.AudioProcessingController;
import io.livekit.android.audio.AudioRecordPrewarmer;
import io.livekit.android.audio.CommunicationWorkaround;
import io.livekit.android.e2ee.E2EEManager;
import io.livekit.android.memory.CloseableManager;
import io.livekit.android.room.datastream.incoming.IncomingDataStreamManager;
import io.livekit.android.room.network.NetworkCallbackManager;
import io.livekit.android.room.participant.LocalParticipant;
import io.livekit.android.room.participant.RemoteParticipant;
import io.livekit.android.room.provisions.LKObjects;
import io.livekit.android.room.util.ConnectionWarmer;
import javax.inject.Provider;
import kotlin.jvm.functions.Function1;
import kotlinx.coroutines.CoroutineDispatcher;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.audio.AudioDeviceModule;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class Room_Factory {
  private final Provider<RTCEngine> engineProvider;

  private final Provider<EglBase> eglBaseProvider;

  private final Provider<LocalParticipant.Factory> localParticipantFactoryProvider;

  private final Provider<DefaultsManager> defaultsManagerProvider;

  private final Provider<CoroutineDispatcher> defaultDispatcherProvider;

  private final Provider<CoroutineDispatcher> ioDispatcherProvider;

  private final Provider<AudioHandler> audioHandlerProvider;

  private final Provider<CloseableManager> closeableManagerProvider;

  private final Provider<E2EEManager.Factory> e2EEManagerFactoryProvider;

  private final Provider<CommunicationWorkaround> communicationWorkaroundProvider;

  private final Provider<AudioProcessingController> audioProcessingControllerProvider;

  private final Provider<LKObjects> lkObjectsProvider;

  private final Provider<Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager>> networkCallbackManagerFactoryProvider;

  private final Provider<AudioDeviceModule> audioDeviceModuleProvider;

  private final Provider<RegionUrlProvider.Factory> regionUrlProviderFactoryProvider;

  private final Provider<ConnectionWarmer> connectionWarmerProvider;

  private final Provider<AudioRecordPrewarmer> audioRecordPrewarmerProvider;

  private final Provider<IncomingDataStreamManager> incomingDataStreamManagerProvider;

  private final Provider<RemoteParticipant.Factory> remoteParticipantFactoryProvider;

  public Room_Factory(Provider<RTCEngine> engineProvider, Provider<EglBase> eglBaseProvider,
      Provider<LocalParticipant.Factory> localParticipantFactoryProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<CoroutineDispatcher> defaultDispatcherProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<AudioHandler> audioHandlerProvider,
      Provider<CloseableManager> closeableManagerProvider,
      Provider<E2EEManager.Factory> e2EEManagerFactoryProvider,
      Provider<CommunicationWorkaround> communicationWorkaroundProvider,
      Provider<AudioProcessingController> audioProcessingControllerProvider,
      Provider<LKObjects> lkObjectsProvider,
      Provider<Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager>> networkCallbackManagerFactoryProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider,
      Provider<RegionUrlProvider.Factory> regionUrlProviderFactoryProvider,
      Provider<ConnectionWarmer> connectionWarmerProvider,
      Provider<AudioRecordPrewarmer> audioRecordPrewarmerProvider,
      Provider<IncomingDataStreamManager> incomingDataStreamManagerProvider,
      Provider<RemoteParticipant.Factory> remoteParticipantFactoryProvider) {
    this.engineProvider = engineProvider;
    this.eglBaseProvider = eglBaseProvider;
    this.localParticipantFactoryProvider = localParticipantFactoryProvider;
    this.defaultsManagerProvider = defaultsManagerProvider;
    this.defaultDispatcherProvider = defaultDispatcherProvider;
    this.ioDispatcherProvider = ioDispatcherProvider;
    this.audioHandlerProvider = audioHandlerProvider;
    this.closeableManagerProvider = closeableManagerProvider;
    this.e2EEManagerFactoryProvider = e2EEManagerFactoryProvider;
    this.communicationWorkaroundProvider = communicationWorkaroundProvider;
    this.audioProcessingControllerProvider = audioProcessingControllerProvider;
    this.lkObjectsProvider = lkObjectsProvider;
    this.networkCallbackManagerFactoryProvider = networkCallbackManagerFactoryProvider;
    this.audioDeviceModuleProvider = audioDeviceModuleProvider;
    this.regionUrlProviderFactoryProvider = regionUrlProviderFactoryProvider;
    this.connectionWarmerProvider = connectionWarmerProvider;
    this.audioRecordPrewarmerProvider = audioRecordPrewarmerProvider;
    this.incomingDataStreamManagerProvider = incomingDataStreamManagerProvider;
    this.remoteParticipantFactoryProvider = remoteParticipantFactoryProvider;
  }

  public Room get(Context context) {
    return newInstance(context, engineProvider.get(), eglBaseProvider.get(), localParticipantFactoryProvider.get(), defaultsManagerProvider.get(), defaultDispatcherProvider.get(), ioDispatcherProvider.get(), audioHandlerProvider.get(), closeableManagerProvider.get(), e2EEManagerFactoryProvider.get(), communicationWorkaroundProvider.get(), audioProcessingControllerProvider.get(), lkObjectsProvider.get(), networkCallbackManagerFactoryProvider.get(), audioDeviceModuleProvider.get(), regionUrlProviderFactoryProvider.get(), connectionWarmerProvider.get(), audioRecordPrewarmerProvider.get(), incomingDataStreamManagerProvider.get(), remoteParticipantFactoryProvider.get());
  }

  public static Room_Factory create(Provider<RTCEngine> engineProvider,
      Provider<EglBase> eglBaseProvider,
      Provider<LocalParticipant.Factory> localParticipantFactoryProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<CoroutineDispatcher> defaultDispatcherProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<AudioHandler> audioHandlerProvider,
      Provider<CloseableManager> closeableManagerProvider,
      Provider<E2EEManager.Factory> e2EEManagerFactoryProvider,
      Provider<CommunicationWorkaround> communicationWorkaroundProvider,
      Provider<AudioProcessingController> audioProcessingControllerProvider,
      Provider<LKObjects> lkObjectsProvider,
      Provider<Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager>> networkCallbackManagerFactoryProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider,
      Provider<RegionUrlProvider.Factory> regionUrlProviderFactoryProvider,
      Provider<ConnectionWarmer> connectionWarmerProvider,
      Provider<AudioRecordPrewarmer> audioRecordPrewarmerProvider,
      Provider<IncomingDataStreamManager> incomingDataStreamManagerProvider,
      Provider<RemoteParticipant.Factory> remoteParticipantFactoryProvider) {
    return new Room_Factory(engineProvider, eglBaseProvider, localParticipantFactoryProvider, defaultsManagerProvider, defaultDispatcherProvider, ioDispatcherProvider, audioHandlerProvider, closeableManagerProvider, e2EEManagerFactoryProvider, communicationWorkaroundProvider, audioProcessingControllerProvider, lkObjectsProvider, networkCallbackManagerFactoryProvider, audioDeviceModuleProvider, regionUrlProviderFactoryProvider, connectionWarmerProvider, audioRecordPrewarmerProvider, incomingDataStreamManagerProvider, remoteParticipantFactoryProvider);
  }

  public static Room newInstance(Context context, RTCEngine engine, EglBase eglBase,
      LocalParticipant.Factory localParticipantFactory, DefaultsManager defaultsManager,
      CoroutineDispatcher defaultDispatcher, CoroutineDispatcher ioDispatcher,
      AudioHandler audioHandler, CloseableManager closeableManager,
      E2EEManager.Factory e2EEManagerFactory, CommunicationWorkaround communicationWorkaround,
      AudioProcessingController audioProcessingController, LKObjects lkObjects,
      Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager> networkCallbackManagerFactory,
      AudioDeviceModule audioDeviceModule, RegionUrlProvider.Factory regionUrlProviderFactory,
      ConnectionWarmer connectionWarmer, AudioRecordPrewarmer audioRecordPrewarmer,
      IncomingDataStreamManager incomingDataStreamManager,
      RemoteParticipant.Factory remoteParticipantFactory) {
    return new Room(context, engine, eglBase, localParticipantFactory, defaultsManager, defaultDispatcher, ioDispatcher, audioHandler, closeableManager, e2EEManagerFactory, communicationWorkaround, audioProcessingController, lkObjects, networkCallbackManagerFactory, audioDeviceModule, regionUrlProviderFactory, connectionWarmer, audioRecordPrewarmer, incomingDataStreamManager, remoteParticipantFactory);
  }
}
