// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class Room_Factory_Impl implements Room.Factory {
  private final Room_Factory delegateFactory;

  Room_Factory_Impl(Room_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public Room create(Context context) {
    return delegateFactory.get(context);
  }

  public static Provider<Room.Factory> create(Room_Factory delegateFactory) {
    return InstanceFactory.create(new Room_Factory_Impl(delegateFactory));
  }
}
