// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.e2ee.DataPacketCryptorManager;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCEngine_Factory implements Factory<RTCEngine> {
  private final Provider<SignalClient> clientProvider;

  private final Provider<PeerConnectionTransport.Factory> pctFactoryProvider;

  private final Provider<CoroutineDispatcher> ioDispatcherProvider;

  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  private final Provider<DataPacketCryptorManager.Factory> dataPacketCryptorFactoryProvider;

  public RTCEngine_Factory(Provider<SignalClient> clientProvider,
      Provider<PeerConnectionTransport.Factory> pctFactoryProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider,
      Provider<DataPacketCryptorManager.Factory> dataPacketCryptorFactoryProvider) {
    this.clientProvider = clientProvider;
    this.pctFactoryProvider = pctFactoryProvider;
    this.ioDispatcherProvider = ioDispatcherProvider;
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
    this.dataPacketCryptorFactoryProvider = dataPacketCryptorFactoryProvider;
  }

  @Override
  public RTCEngine get() {
    return newInstance(clientProvider.get(), pctFactoryProvider.get(), ioDispatcherProvider.get(), rtcThreadTokenProvider.get(), dataPacketCryptorFactoryProvider.get());
  }

  public static RTCEngine_Factory create(Provider<SignalClient> clientProvider,
      Provider<PeerConnectionTransport.Factory> pctFactoryProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider,
      Provider<DataPacketCryptorManager.Factory> dataPacketCryptorFactoryProvider) {
    return new RTCEngine_Factory(clientProvider, pctFactoryProvider, ioDispatcherProvider, rtcThreadTokenProvider, dataPacketCryptorFactoryProvider);
  }

  public static RTCEngine newInstance(SignalClient client,
      PeerConnectionTransport.Factory pctFactory, CoroutineDispatcher ioDispatcher,
      RTCThreadToken rtcThreadToken, DataPacketCryptorManager.Factory dataPacketCryptorFactory) {
    return new RTCEngine(client, pctFactory, ioDispatcher, rtcThreadToken, dataPacketCryptorFactory);
  }
}
