// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.stats.NetworkInfo;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;
import kotlinx.serialization.json.Json;
import okhttp3.OkHttpClient;
import okhttp3.WebSocket;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class SignalClient_Factory implements Factory<SignalClient> {
  private final Provider<WebSocket.Factory> websocketFactoryProvider;

  private final Provider<Json> jsonProvider;

  private final Provider<OkHttpClient> okHttpClientProvider;

  private final Provider<CoroutineDispatcher> ioDispatcherProvider;

  private final Provider<NetworkInfo> networkInfoProvider;

  public SignalClient_Factory(Provider<WebSocket.Factory> websocketFactoryProvider,
      Provider<Json> jsonProvider, Provider<OkHttpClient> okHttpClientProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<NetworkInfo> networkInfoProvider) {
    this.websocketFactoryProvider = websocketFactoryProvider;
    this.jsonProvider = jsonProvider;
    this.okHttpClientProvider = okHttpClientProvider;
    this.ioDispatcherProvider = ioDispatcherProvider;
    this.networkInfoProvider = networkInfoProvider;
  }

  @Override
  public SignalClient get() {
    return newInstance(websocketFactoryProvider.get(), jsonProvider.get(), okHttpClientProvider.get(), ioDispatcherProvider.get(), networkInfoProvider.get());
  }

  public static SignalClient_Factory create(Provider<WebSocket.Factory> websocketFactoryProvider,
      Provider<Json> jsonProvider, Provider<OkHttpClient> okHttpClientProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<NetworkInfo> networkInfoProvider) {
    return new SignalClient_Factory(websocketFactoryProvider, jsonProvider, okHttpClientProvider, ioDispatcherProvider, networkInfoProvider);
  }

  public static SignalClient newInstance(WebSocket.Factory websocketFactory, Json json,
      OkHttpClient okHttpClient, CoroutineDispatcher ioDispatcher, NetworkInfo networkInfo) {
    return new SignalClient(websocketFactory, json, okHttpClient, ioDispatcher, networkInfo);
  }
}
