// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.datastream.outgoing;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.RTCEngine;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OutgoingDataStreamManagerImpl_Factory implements Factory<OutgoingDataStreamManagerImpl> {
  private final Provider<RTCEngine> engineProvider;

  public OutgoingDataStreamManagerImpl_Factory(Provider<RTCEngine> engineProvider) {
    this.engineProvider = engineProvider;
  }

  @Override
  public OutgoingDataStreamManagerImpl get() {
    return newInstance(engineProvider.get());
  }

  public static OutgoingDataStreamManagerImpl_Factory create(Provider<RTCEngine> engineProvider) {
    return new OutgoingDataStreamManagerImpl_Factory(engineProvider);
  }

  public static OutgoingDataStreamManagerImpl newInstance(RTCEngine engine) {
    return new OutgoingDataStreamManagerImpl(engine);
  }
}
