// Generated by Dagger (https://dagger.dev).
package io.livekit.android.e2ee;

import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import livekit.org.webrtc.PeerConnectionFactory;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class E2EEManager_Factory {
  private final Provider<PeerConnectionFactory> peerConnectionFactoryProvider;

  private final Provider<DataPacketCryptorManager.Factory> dataPacketCryptorManagerFactoryProvider;

  public E2EEManager_Factory(Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<DataPacketCryptorManager.Factory> dataPacketCryptorManagerFactoryProvider) {
    this.peerConnectionFactoryProvider = peerConnectionFactoryProvider;
    this.dataPacketCryptorManagerFactoryProvider = dataPacketCryptorManagerFactoryProvider;
  }

  public E2EEManager get(KeyProvider keyProvider) {
    return newInstance(keyProvider, peerConnectionFactoryProvider.get(), dataPacketCryptorManagerFactoryProvider.get());
  }

  public static E2EEManager_Factory create(
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<DataPacketCryptorManager.Factory> dataPacketCryptorManagerFactoryProvider) {
    return new E2EEManager_Factory(peerConnectionFactoryProvider, dataPacketCryptorManagerFactoryProvider);
  }

  public static E2EEManager newInstance(KeyProvider keyProvider,
      PeerConnectionFactory peerConnectionFactory,
      DataPacketCryptorManager.Factory dataPacketCryptorManagerFactory) {
    return new E2EEManager(keyProvider, peerConnectionFactory, dataPacketCryptorManagerFactory);
  }
}
