// Generated by Dagger (https://dagger.dev).
package io.livekit.android.e2ee;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class E2EEManager_Factory_Impl implements E2EEManager.Factory {
  private final E2EEManager_Factory delegateFactory;

  E2EEManager_Factory_Impl(E2EEManager_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public E2EEManager create(KeyProvider keyProvider) {
    return delegateFactory.get(keyProvider);
  }

  public static Provider<E2EEManager.Factory> create(E2EEManager_Factory delegateFactory) {
    return InstanceFactory.create(new E2EEManager_Factory_Impl(delegateFactory));
  }
}
