// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.util;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import okhttp3.OkHttpClient;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OkHttpConnectionWarmer_Factory implements Factory<OkHttpConnectionWarmer> {
  private final Provider<OkHttpClient> okHttpClientProvider;

  public OkHttpConnectionWarmer_Factory(Provider<OkHttpClient> okHttpClientProvider) {
    this.okHttpClientProvider = okHttpClientProvider;
  }

  @Override
  public OkHttpConnectionWarmer get() {
    return newInstance(okHttpClientProvider.get());
  }

  public static OkHttpConnectionWarmer_Factory create(Provider<OkHttpClient> okHttpClientProvider) {
    return new OkHttpConnectionWarmer_Factory(okHttpClientProvider);
  }

  public static OkHttpConnectionWarmer newInstance(OkHttpClient okHttpClient) {
    return new OkHttpConnectionWarmer(okHttpClient);
  }
}
