// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livekit_token_source.proto

package livekit;

public final class LivekitTokenSource {
  private LivekitTokenSource() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TokenSourceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:livekit.TokenSourceRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @return Whether the roomName field is set.
     */
    boolean hasRoomName();
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @return The roomName.
     */
    java.lang.String getRoomName();
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @return The bytes for roomName.
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();

    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @return Whether the participantName field is set.
     */
    boolean hasParticipantName();
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @return The participantName.
     */
    java.lang.String getParticipantName();
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @return The bytes for participantName.
     */
    com.google.protobuf.ByteString
        getParticipantNameBytes();

    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @return Whether the participantIdentity field is set.
     */
    boolean hasParticipantIdentity();
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @return The participantIdentity.
     */
    java.lang.String getParticipantIdentity();
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @return The bytes for participantIdentity.
     */
    com.google.protobuf.ByteString
        getParticipantIdentityBytes();

    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @return Whether the participantMetadata field is set.
     */
    boolean hasParticipantMetadata();
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @return The participantMetadata.
     */
    java.lang.String getParticipantMetadata();
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @return The bytes for participantMetadata.
     */
    com.google.protobuf.ByteString
        getParticipantMetadataBytes();

    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    int getParticipantAttributesCount();
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    boolean containsParticipantAttributes(
        java.lang.String key);
    /**
     * Use {@link #getParticipantAttributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getParticipantAttributes();
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParticipantAttributesMap();
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */

    /* nullable */
java.lang.String getParticipantAttributesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */

    java.lang.String getParticipantAttributesOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     * @return Whether the roomConfig field is set.
     */
    boolean hasRoomConfig();
    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     * @return The roomConfig.
     */
    livekit.LivekitRoom.RoomConfiguration getRoomConfig();
  }
  /**
   * Protobuf type {@code livekit.TokenSourceRequest}
   */
  public  static final class TokenSourceRequest extends
      com.google.protobuf.GeneratedMessageLite<
          TokenSourceRequest, TokenSourceRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:livekit.TokenSourceRequest)
      TokenSourceRequestOrBuilder {
    private TokenSourceRequest() {
      roomName_ = "";
      participantName_ = "";
      participantIdentity_ = "";
      participantMetadata_ = "";
    }
    private int bitField0_;
    public static final int ROOM_NAME_FIELD_NUMBER = 1;
    private java.lang.String roomName_;
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @return Whether the roomName field is set.
     */
    @java.lang.Override
    public boolean hasRoomName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @return The roomName.
     */
    @java.lang.Override
    public java.lang.String getRoomName() {
      return roomName_;
    }
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @return The bytes for roomName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(roomName_);
    }
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @param value The roomName to set.
     */
    private void setRoomName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      roomName_ = value;
    }
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     */
    private void clearRoomName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      roomName_ = getDefaultInstance().getRoomName();
    }
    /**
     * <pre>
     * The name of the room being requested when generating credentials
     * </pre>
     *
     * <code>optional string room_name = 1;</code>
     * @param value The bytes for roomName to set.
     */
    private void setRoomNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      roomName_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int PARTICIPANT_NAME_FIELD_NUMBER = 2;
    private java.lang.String participantName_;
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @return Whether the participantName field is set.
     */
    @java.lang.Override
    public boolean hasParticipantName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @return The participantName.
     */
    @java.lang.Override
    public java.lang.String getParticipantName() {
      return participantName_;
    }
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @return The bytes for participantName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParticipantNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(participantName_);
    }
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @param value The participantName to set.
     */
    private void setParticipantName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      participantName_ = value;
    }
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     */
    private void clearParticipantName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      participantName_ = getDefaultInstance().getParticipantName();
    }
    /**
     * <pre>
     * The name of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_name = 2;</code>
     * @param value The bytes for participantName to set.
     */
    private void setParticipantNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      participantName_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int PARTICIPANT_IDENTITY_FIELD_NUMBER = 3;
    private java.lang.String participantIdentity_;
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @return Whether the participantIdentity field is set.
     */
    @java.lang.Override
    public boolean hasParticipantIdentity() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @return The participantIdentity.
     */
    @java.lang.Override
    public java.lang.String getParticipantIdentity() {
      return participantIdentity_;
    }
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @return The bytes for participantIdentity.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParticipantIdentityBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(participantIdentity_);
    }
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @param value The participantIdentity to set.
     */
    private void setParticipantIdentity(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      participantIdentity_ = value;
    }
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     */
    private void clearParticipantIdentity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      participantIdentity_ = getDefaultInstance().getParticipantIdentity();
    }
    /**
     * <pre>
     * The identity of the participant being requested for this client when generating credentials
     * </pre>
     *
     * <code>optional string participant_identity = 3;</code>
     * @param value The bytes for participantIdentity to set.
     */
    private void setParticipantIdentityBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      participantIdentity_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int PARTICIPANT_METADATA_FIELD_NUMBER = 4;
    private java.lang.String participantMetadata_;
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @return Whether the participantMetadata field is set.
     */
    @java.lang.Override
    public boolean hasParticipantMetadata() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @return The participantMetadata.
     */
    @java.lang.Override
    public java.lang.String getParticipantMetadata() {
      return participantMetadata_;
    }
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @return The bytes for participantMetadata.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParticipantMetadataBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(participantMetadata_);
    }
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @param value The participantMetadata to set.
     */
    private void setParticipantMetadata(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000008;
      participantMetadata_ = value;
    }
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     */
    private void clearParticipantMetadata() {
      bitField0_ = (bitField0_ & ~0x00000008);
      participantMetadata_ = getDefaultInstance().getParticipantMetadata();
    }
    /**
     * <pre>
     * Any participant metadata being included along with the credentials generation operation
     * </pre>
     *
     * <code>optional string participant_metadata = 4;</code>
     * @param value The bytes for participantMetadata to set.
     */
    private void setParticipantMetadataBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      participantMetadata_ = value.toStringUtf8();
      bitField0_ |= 0x00000008;
    }

    public static final int PARTICIPANT_ATTRIBUTES_FIELD_NUMBER = 5;
    private static final class ParticipantAttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> participantAttributes_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetParticipantAttributes() {
      return participantAttributes_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableParticipantAttributes() {
      if (!participantAttributes_.isMutable()) {
        participantAttributes_ = participantAttributes_.mutableCopy();
      }
      return participantAttributes_;
    }
    @java.lang.Override

    public int getParticipantAttributesCount() {
      return internalGetParticipantAttributes().size();
    }
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    @java.lang.Override

    public boolean containsParticipantAttributes(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return internalGetParticipantAttributes().containsKey(key);
    }
    /**
     * Use {@link #getParticipantAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParticipantAttributes() {
      return getParticipantAttributesMap();
    }
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getParticipantAttributesMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetParticipantAttributes());
    }
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getParticipantAttributesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParticipantAttributes();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getParticipantAttributesOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParticipantAttributes();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * Any participant attributes being included along with the credentials generation operation
     * </pre>
     *
     * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutableParticipantAttributesMap() {
      return internalGetMutableParticipantAttributes();
    }

    public static final int ROOM_CONFIG_FIELD_NUMBER = 6;
    private livekit.LivekitRoom.RoomConfiguration roomConfig_;
    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     */
    @java.lang.Override
    public boolean hasRoomConfig() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     */
    @java.lang.Override
    public livekit.LivekitRoom.RoomConfiguration getRoomConfig() {
      return roomConfig_ == null ? livekit.LivekitRoom.RoomConfiguration.getDefaultInstance() : roomConfig_;
    }
    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     */
    private void setRoomConfig(livekit.LivekitRoom.RoomConfiguration value) {
      value.getClass();
  roomConfig_ = value;
      bitField0_ |= 0x00000010;
      }
    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeRoomConfig(livekit.LivekitRoom.RoomConfiguration value) {
      value.getClass();
  if (roomConfig_ != null &&
          roomConfig_ != livekit.LivekitRoom.RoomConfiguration.getDefaultInstance()) {
        roomConfig_ =
          livekit.LivekitRoom.RoomConfiguration.newBuilder(roomConfig_).mergeFrom(value).buildPartial();
      } else {
        roomConfig_ = value;
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * A RoomConfiguration object can be passed to request extra parameters should be included when
     * generating connection credentials - dispatching agents, defining egress settings, etc
     * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
     * </pre>
     *
     * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
     */
    private void clearRoomConfig() {  roomConfig_ = null;
      bitField0_ = (bitField0_ & ~0x00000010);
    }

    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitTokenSource.TokenSourceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(livekit.LivekitTokenSource.TokenSourceRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code livekit.TokenSourceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          livekit.LivekitTokenSource.TokenSourceRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:livekit.TokenSourceRequest)
        livekit.LivekitTokenSource.TokenSourceRequestOrBuilder {
      // Construct using livekit.LivekitTokenSource.TokenSourceRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * The name of the room being requested when generating credentials
       * </pre>
       *
       * <code>optional string room_name = 1;</code>
       * @return Whether the roomName field is set.
       */
      @java.lang.Override
      public boolean hasRoomName() {
        return instance.hasRoomName();
      }
      /**
       * <pre>
       * The name of the room being requested when generating credentials
       * </pre>
       *
       * <code>optional string room_name = 1;</code>
       * @return The roomName.
       */
      @java.lang.Override
      public java.lang.String getRoomName() {
        return instance.getRoomName();
      }
      /**
       * <pre>
       * The name of the room being requested when generating credentials
       * </pre>
       *
       * <code>optional string room_name = 1;</code>
       * @return The bytes for roomName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        return instance.getRoomNameBytes();
      }
      /**
       * <pre>
       * The name of the room being requested when generating credentials
       * </pre>
       *
       * <code>optional string room_name = 1;</code>
       * @param value The roomName to set.
       * @return This builder for chaining.
       */
      public Builder setRoomName(
          java.lang.String value) {
        copyOnWrite();
        instance.setRoomName(value);
        return this;
      }
      /**
       * <pre>
       * The name of the room being requested when generating credentials
       * </pre>
       *
       * <code>optional string room_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomName() {
        copyOnWrite();
        instance.clearRoomName();
        return this;
      }
      /**
       * <pre>
       * The name of the room being requested when generating credentials
       * </pre>
       *
       * <code>optional string room_name = 1;</code>
       * @param value The bytes for roomName to set.
       * @return This builder for chaining.
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRoomNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * The name of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_name = 2;</code>
       * @return Whether the participantName field is set.
       */
      @java.lang.Override
      public boolean hasParticipantName() {
        return instance.hasParticipantName();
      }
      /**
       * <pre>
       * The name of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_name = 2;</code>
       * @return The participantName.
       */
      @java.lang.Override
      public java.lang.String getParticipantName() {
        return instance.getParticipantName();
      }
      /**
       * <pre>
       * The name of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_name = 2;</code>
       * @return The bytes for participantName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getParticipantNameBytes() {
        return instance.getParticipantNameBytes();
      }
      /**
       * <pre>
       * The name of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_name = 2;</code>
       * @param value The participantName to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantName(
          java.lang.String value) {
        copyOnWrite();
        instance.setParticipantName(value);
        return this;
      }
      /**
       * <pre>
       * The name of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParticipantName() {
        copyOnWrite();
        instance.clearParticipantName();
        return this;
      }
      /**
       * <pre>
       * The name of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_name = 2;</code>
       * @param value The bytes for participantName to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParticipantNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * The identity of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_identity = 3;</code>
       * @return Whether the participantIdentity field is set.
       */
      @java.lang.Override
      public boolean hasParticipantIdentity() {
        return instance.hasParticipantIdentity();
      }
      /**
       * <pre>
       * The identity of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_identity = 3;</code>
       * @return The participantIdentity.
       */
      @java.lang.Override
      public java.lang.String getParticipantIdentity() {
        return instance.getParticipantIdentity();
      }
      /**
       * <pre>
       * The identity of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_identity = 3;</code>
       * @return The bytes for participantIdentity.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getParticipantIdentityBytes() {
        return instance.getParticipantIdentityBytes();
      }
      /**
       * <pre>
       * The identity of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_identity = 3;</code>
       * @param value The participantIdentity to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantIdentity(
          java.lang.String value) {
        copyOnWrite();
        instance.setParticipantIdentity(value);
        return this;
      }
      /**
       * <pre>
       * The identity of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_identity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParticipantIdentity() {
        copyOnWrite();
        instance.clearParticipantIdentity();
        return this;
      }
      /**
       * <pre>
       * The identity of the participant being requested for this client when generating credentials
       * </pre>
       *
       * <code>optional string participant_identity = 3;</code>
       * @param value The bytes for participantIdentity to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantIdentityBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParticipantIdentityBytes(value);
        return this;
      }

      /**
       * <pre>
       * Any participant metadata being included along with the credentials generation operation
       * </pre>
       *
       * <code>optional string participant_metadata = 4;</code>
       * @return Whether the participantMetadata field is set.
       */
      @java.lang.Override
      public boolean hasParticipantMetadata() {
        return instance.hasParticipantMetadata();
      }
      /**
       * <pre>
       * Any participant metadata being included along with the credentials generation operation
       * </pre>
       *
       * <code>optional string participant_metadata = 4;</code>
       * @return The participantMetadata.
       */
      @java.lang.Override
      public java.lang.String getParticipantMetadata() {
        return instance.getParticipantMetadata();
      }
      /**
       * <pre>
       * Any participant metadata being included along with the credentials generation operation
       * </pre>
       *
       * <code>optional string participant_metadata = 4;</code>
       * @return The bytes for participantMetadata.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getParticipantMetadataBytes() {
        return instance.getParticipantMetadataBytes();
      }
      /**
       * <pre>
       * Any participant metadata being included along with the credentials generation operation
       * </pre>
       *
       * <code>optional string participant_metadata = 4;</code>
       * @param value The participantMetadata to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantMetadata(
          java.lang.String value) {
        copyOnWrite();
        instance.setParticipantMetadata(value);
        return this;
      }
      /**
       * <pre>
       * Any participant metadata being included along with the credentials generation operation
       * </pre>
       *
       * <code>optional string participant_metadata = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParticipantMetadata() {
        copyOnWrite();
        instance.clearParticipantMetadata();
        return this;
      }
      /**
       * <pre>
       * Any participant metadata being included along with the credentials generation operation
       * </pre>
       *
       * <code>optional string participant_metadata = 4;</code>
       * @param value The bytes for participantMetadata to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantMetadataBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParticipantMetadataBytes(value);
        return this;
      }

      @java.lang.Override

      public int getParticipantAttributesCount() {
        return instance.getParticipantAttributesMap().size();
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */
      @java.lang.Override

      public boolean containsParticipantAttributes(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        return instance.getParticipantAttributesMap().containsKey(key);
      }

      public Builder clearParticipantAttributes() {
        copyOnWrite();
        instance.getMutableParticipantAttributesMap().clear();
        return this;
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */

      public Builder removeParticipantAttributes(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        copyOnWrite();
        instance.getMutableParticipantAttributesMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getParticipantAttributesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getParticipantAttributes() {
        return getParticipantAttributesMap();
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getParticipantAttributesMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getParticipantAttributesMap());
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */
      @java.lang.Override

      public /* nullable */
java.lang.String getParticipantAttributesOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getParticipantAttributesMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getParticipantAttributesOrThrow(
          java.lang.String key) {
        java.lang.Class<?> keyClass = key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getParticipantAttributesMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */
      public Builder putParticipantAttributes(
          java.lang.String key,
          java.lang.String value) {
        java.lang.Class<?> keyClass = key.getClass();
        java.lang.Class<?> valueClass = value.getClass();
        copyOnWrite();
        instance.getMutableParticipantAttributesMap().put(key, value);
        return this;
      }
      /**
       * <pre>
       * Any participant attributes being included along with the credentials generation operation
       * </pre>
       *
       * <code>map&lt;string, string&gt; participant_attributes = 5;</code>
       */
      public Builder putAllParticipantAttributes(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutableParticipantAttributesMap().putAll(values);
        return this;
      }

      /**
       * <pre>
       * A RoomConfiguration object can be passed to request extra parameters should be included when
       * generating connection credentials - dispatching agents, defining egress settings, etc
       * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
       * </pre>
       *
       * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
       */
      @java.lang.Override
      public boolean hasRoomConfig() {
        return instance.hasRoomConfig();
      }
      /**
       * <pre>
       * A RoomConfiguration object can be passed to request extra parameters should be included when
       * generating connection credentials - dispatching agents, defining egress settings, etc
       * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
       * </pre>
       *
       * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
       */
      @java.lang.Override
      public livekit.LivekitRoom.RoomConfiguration getRoomConfig() {
        return instance.getRoomConfig();
      }
      /**
       * <pre>
       * A RoomConfiguration object can be passed to request extra parameters should be included when
       * generating connection credentials - dispatching agents, defining egress settings, etc
       * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
       * </pre>
       *
       * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
       */
      public Builder setRoomConfig(livekit.LivekitRoom.RoomConfiguration value) {
        copyOnWrite();
        instance.setRoomConfig(value);
        return this;
        }
      /**
       * <pre>
       * A RoomConfiguration object can be passed to request extra parameters should be included when
       * generating connection credentials - dispatching agents, defining egress settings, etc
       * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
       * </pre>
       *
       * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
       */
      public Builder setRoomConfig(
          livekit.LivekitRoom.RoomConfiguration.Builder builderForValue) {
        copyOnWrite();
        instance.setRoomConfig(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * A RoomConfiguration object can be passed to request extra parameters should be included when
       * generating connection credentials - dispatching agents, defining egress settings, etc
       * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
       * </pre>
       *
       * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
       */
      public Builder mergeRoomConfig(livekit.LivekitRoom.RoomConfiguration value) {
        copyOnWrite();
        instance.mergeRoomConfig(value);
        return this;
      }
      /**
       * <pre>
       * A RoomConfiguration object can be passed to request extra parameters should be included when
       * generating connection credentials - dispatching agents, defining egress settings, etc
       * More info: https://docs.livekit.io/home/get-started/authentication/#room-configuration
       * </pre>
       *
       * <code>optional .livekit.RoomConfiguration room_config = 6;</code>
       */
      public Builder clearRoomConfig() {  copyOnWrite();
        instance.clearRoomConfig();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:livekit.TokenSourceRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new livekit.LivekitTokenSource.TokenSourceRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "roomName_",
              "participantName_",
              "participantIdentity_",
              "participantMetadata_",
              "participantAttributes_",
              ParticipantAttributesDefaultEntryHolder.defaultEntry,
              "roomConfig_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0001\u0000\u0000\u0001\u1208\u0000\u0002" +
                "\u1208\u0001\u0003\u1208\u0002\u0004\u1208\u0003\u00052\u0006\u1009\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<livekit.LivekitTokenSource.TokenSourceRequest> parser = PARSER;
          if (parser == null) {
            synchronized (livekit.LivekitTokenSource.TokenSourceRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<livekit.LivekitTokenSource.TokenSourceRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:livekit.TokenSourceRequest)
    private static final livekit.LivekitTokenSource.TokenSourceRequest DEFAULT_INSTANCE;
    static {
      TokenSourceRequest defaultInstance = new TokenSourceRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        TokenSourceRequest.class, defaultInstance);
    }

    public static livekit.LivekitTokenSource.TokenSourceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TokenSourceRequest> PARSER;

    public static com.google.protobuf.Parser<TokenSourceRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface TokenSourceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:livekit.TokenSourceResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string server_url = 1;</code>
     * @return The serverUrl.
     */
    java.lang.String getServerUrl();
    /**
     * <code>string server_url = 1;</code>
     * @return The bytes for serverUrl.
     */
    com.google.protobuf.ByteString
        getServerUrlBytes();

    /**
     * <code>string participant_token = 2;</code>
     * @return The participantToken.
     */
    java.lang.String getParticipantToken();
    /**
     * <code>string participant_token = 2;</code>
     * @return The bytes for participantToken.
     */
    com.google.protobuf.ByteString
        getParticipantTokenBytes();
  }
  /**
   * Protobuf type {@code livekit.TokenSourceResponse}
   */
  public  static final class TokenSourceResponse extends
      com.google.protobuf.GeneratedMessageLite<
          TokenSourceResponse, TokenSourceResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:livekit.TokenSourceResponse)
      TokenSourceResponseOrBuilder {
    private TokenSourceResponse() {
      serverUrl_ = "";
      participantToken_ = "";
    }
    public static final int SERVER_URL_FIELD_NUMBER = 1;
    private java.lang.String serverUrl_;
    /**
     * <code>string server_url = 1;</code>
     * @return The serverUrl.
     */
    @java.lang.Override
    public java.lang.String getServerUrl() {
      return serverUrl_;
    }
    /**
     * <code>string server_url = 1;</code>
     * @return The bytes for serverUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serverUrl_);
    }
    /**
     * <code>string server_url = 1;</code>
     * @param value The serverUrl to set.
     */
    private void setServerUrl(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      serverUrl_ = value;
    }
    /**
     * <code>string server_url = 1;</code>
     */
    private void clearServerUrl() {

      serverUrl_ = getDefaultInstance().getServerUrl();
    }
    /**
     * <code>string server_url = 1;</code>
     * @param value The bytes for serverUrl to set.
     */
    private void setServerUrlBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      serverUrl_ = value.toStringUtf8();

    }

    public static final int PARTICIPANT_TOKEN_FIELD_NUMBER = 2;
    private java.lang.String participantToken_;
    /**
     * <code>string participant_token = 2;</code>
     * @return The participantToken.
     */
    @java.lang.Override
    public java.lang.String getParticipantToken() {
      return participantToken_;
    }
    /**
     * <code>string participant_token = 2;</code>
     * @return The bytes for participantToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParticipantTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(participantToken_);
    }
    /**
     * <code>string participant_token = 2;</code>
     * @param value The participantToken to set.
     */
    private void setParticipantToken(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      participantToken_ = value;
    }
    /**
     * <code>string participant_token = 2;</code>
     */
    private void clearParticipantToken() {

      participantToken_ = getDefaultInstance().getParticipantToken();
    }
    /**
     * <code>string participant_token = 2;</code>
     * @param value The bytes for participantToken to set.
     */
    private void setParticipantTokenBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      participantToken_ = value.toStringUtf8();

    }

    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitTokenSource.TokenSourceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(livekit.LivekitTokenSource.TokenSourceResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code livekit.TokenSourceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          livekit.LivekitTokenSource.TokenSourceResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:livekit.TokenSourceResponse)
        livekit.LivekitTokenSource.TokenSourceResponseOrBuilder {
      // Construct using livekit.LivekitTokenSource.TokenSourceResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string server_url = 1;</code>
       * @return The serverUrl.
       */
      @java.lang.Override
      public java.lang.String getServerUrl() {
        return instance.getServerUrl();
      }
      /**
       * <code>string server_url = 1;</code>
       * @return The bytes for serverUrl.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getServerUrlBytes() {
        return instance.getServerUrlBytes();
      }
      /**
       * <code>string server_url = 1;</code>
       * @param value The serverUrl to set.
       * @return This builder for chaining.
       */
      public Builder setServerUrl(
          java.lang.String value) {
        copyOnWrite();
        instance.setServerUrl(value);
        return this;
      }
      /**
       * <code>string server_url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerUrl() {
        copyOnWrite();
        instance.clearServerUrl();
        return this;
      }
      /**
       * <code>string server_url = 1;</code>
       * @param value The bytes for serverUrl to set.
       * @return This builder for chaining.
       */
      public Builder setServerUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServerUrlBytes(value);
        return this;
      }

      /**
       * <code>string participant_token = 2;</code>
       * @return The participantToken.
       */
      @java.lang.Override
      public java.lang.String getParticipantToken() {
        return instance.getParticipantToken();
      }
      /**
       * <code>string participant_token = 2;</code>
       * @return The bytes for participantToken.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getParticipantTokenBytes() {
        return instance.getParticipantTokenBytes();
      }
      /**
       * <code>string participant_token = 2;</code>
       * @param value The participantToken to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setParticipantToken(value);
        return this;
      }
      /**
       * <code>string participant_token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParticipantToken() {
        copyOnWrite();
        instance.clearParticipantToken();
        return this;
      }
      /**
       * <code>string participant_token = 2;</code>
       * @param value The bytes for participantToken to set.
       * @return This builder for chaining.
       */
      public Builder setParticipantTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setParticipantTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:livekit.TokenSourceResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new livekit.LivekitTokenSource.TokenSourceResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "serverUrl_",
              "participantToken_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<livekit.LivekitTokenSource.TokenSourceResponse> parser = PARSER;
          if (parser == null) {
            synchronized (livekit.LivekitTokenSource.TokenSourceResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<livekit.LivekitTokenSource.TokenSourceResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:livekit.TokenSourceResponse)
    private static final livekit.LivekitTokenSource.TokenSourceResponse DEFAULT_INSTANCE;
    static {
      TokenSourceResponse defaultInstance = new TokenSourceResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        TokenSourceResponse.class, defaultInstance);
    }

    public static livekit.LivekitTokenSource.TokenSourceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TokenSourceResponse> PARSER;

    public static com.google.protobuf.Parser<TokenSourceResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
