// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livekit_webhook.proto

package livekit;

public final class LivekitWebhook {
  private LivekitWebhook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface WebhookEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:livekit.WebhookEvent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     * @return The event.
     */
    java.lang.String getEvent();
    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     * @return The bytes for event.
     */
    com.google.protobuf.ByteString
        getEventBytes();

    /**
     * <code>.livekit.Room room = 2;</code>
     * @return Whether the room field is set.
     */
    boolean hasRoom();
    /**
     * <code>.livekit.Room room = 2;</code>
     * @return The room.
     */
    livekit.LivekitModels.Room getRoom();

    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     * @return Whether the participant field is set.
     */
    boolean hasParticipant();
    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     * @return The participant.
     */
    livekit.LivekitModels.ParticipantInfo getParticipant();

    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     * @return Whether the egressInfo field is set.
     */
    boolean hasEgressInfo();
    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     * @return The egressInfo.
     */
    livekit.LivekitEgress.EgressInfo getEgressInfo();

    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     * @return Whether the ingressInfo field is set.
     */
    boolean hasIngressInfo();
    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     * @return The ingressInfo.
     */
    livekit.LivekitIngress.IngressInfo getIngressInfo();

    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     * @return Whether the track field is set.
     */
    boolean hasTrack();
    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     * @return The track.
     */
    livekit.LivekitModels.TrackInfo getTrack();

    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * timestamp in seconds
     * </pre>
     *
     * <code>int64 created_at = 7;</code>
     * @return The createdAt.
     */
    long getCreatedAt();

    /**
     * <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
     *     See livekit_webhook.proto;l=51
     * @return The numDropped.
     */
    @java.lang.Deprecated int getNumDropped();
  }
  /**
   * Protobuf type {@code livekit.WebhookEvent}
   */
  public  static final class WebhookEvent extends
      com.google.protobuf.GeneratedMessageLite<
          WebhookEvent, WebhookEvent.Builder> implements
      // @@protoc_insertion_point(message_implements:livekit.WebhookEvent)
      WebhookEventOrBuilder {
    private WebhookEvent() {
      event_ = "";
      id_ = "";
    }
    public static final int EVENT_FIELD_NUMBER = 1;
    private java.lang.String event_;
    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     * @return The event.
     */
    @java.lang.Override
    public java.lang.String getEvent() {
      return event_;
    }
    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     * @return The bytes for event.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(event_);
    }
    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     * @param value The event to set.
     */
    private void setEvent(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      event_ = value;
    }
    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     */
    private void clearEvent() {

      event_ = getDefaultInstance().getEvent();
    }
    /**
     * <pre>
     * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
     * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
     * ingress_started, ingress_ended
     * </pre>
     *
     * <code>string event = 1;</code>
     * @param value The bytes for event to set.
     */
    private void setEventBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      event_ = value.toStringUtf8();

    }

    public static final int ROOM_FIELD_NUMBER = 2;
    private livekit.LivekitModels.Room room_;
    /**
     * <code>.livekit.Room room = 2;</code>
     */
    @java.lang.Override
    public boolean hasRoom() {
      return room_ != null;
    }
    /**
     * <code>.livekit.Room room = 2;</code>
     */
    @java.lang.Override
    public livekit.LivekitModels.Room getRoom() {
      return room_ == null ? livekit.LivekitModels.Room.getDefaultInstance() : room_;
    }
    /**
     * <code>.livekit.Room room = 2;</code>
     */
    private void setRoom(livekit.LivekitModels.Room value) {
      value.getClass();
  room_ = value;

      }
    /**
     * <code>.livekit.Room room = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeRoom(livekit.LivekitModels.Room value) {
      value.getClass();
  if (room_ != null &&
          room_ != livekit.LivekitModels.Room.getDefaultInstance()) {
        room_ =
          livekit.LivekitModels.Room.newBuilder(room_).mergeFrom(value).buildPartial();
      } else {
        room_ = value;
      }

    }
    /**
     * <code>.livekit.Room room = 2;</code>
     */
    private void clearRoom() {  room_ = null;

    }

    public static final int PARTICIPANT_FIELD_NUMBER = 3;
    private livekit.LivekitModels.ParticipantInfo participant_;
    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    @java.lang.Override
    public boolean hasParticipant() {
      return participant_ != null;
    }
    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    @java.lang.Override
    public livekit.LivekitModels.ParticipantInfo getParticipant() {
      return participant_ == null ? livekit.LivekitModels.ParticipantInfo.getDefaultInstance() : participant_;
    }
    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    private void setParticipant(livekit.LivekitModels.ParticipantInfo value) {
      value.getClass();
  participant_ = value;

      }
    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeParticipant(livekit.LivekitModels.ParticipantInfo value) {
      value.getClass();
  if (participant_ != null &&
          participant_ != livekit.LivekitModels.ParticipantInfo.getDefaultInstance()) {
        participant_ =
          livekit.LivekitModels.ParticipantInfo.newBuilder(participant_).mergeFrom(value).buildPartial();
      } else {
        participant_ = value;
      }

    }
    /**
     * <pre>
     * set when event is participant_* or track_*
     * </pre>
     *
     * <code>.livekit.ParticipantInfo participant = 3;</code>
     */
    private void clearParticipant() {  participant_ = null;

    }

    public static final int EGRESS_INFO_FIELD_NUMBER = 9;
    private livekit.LivekitEgress.EgressInfo egressInfo_;
    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     */
    @java.lang.Override
    public boolean hasEgressInfo() {
      return egressInfo_ != null;
    }
    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     */
    @java.lang.Override
    public livekit.LivekitEgress.EgressInfo getEgressInfo() {
      return egressInfo_ == null ? livekit.LivekitEgress.EgressInfo.getDefaultInstance() : egressInfo_;
    }
    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     */
    private void setEgressInfo(livekit.LivekitEgress.EgressInfo value) {
      value.getClass();
  egressInfo_ = value;

      }
    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeEgressInfo(livekit.LivekitEgress.EgressInfo value) {
      value.getClass();
  if (egressInfo_ != null &&
          egressInfo_ != livekit.LivekitEgress.EgressInfo.getDefaultInstance()) {
        egressInfo_ =
          livekit.LivekitEgress.EgressInfo.newBuilder(egressInfo_).mergeFrom(value).buildPartial();
      } else {
        egressInfo_ = value;
      }

    }
    /**
     * <pre>
     * set when event is egress_*
     * </pre>
     *
     * <code>.livekit.EgressInfo egress_info = 9;</code>
     */
    private void clearEgressInfo() {  egressInfo_ = null;

    }

    public static final int INGRESS_INFO_FIELD_NUMBER = 10;
    private livekit.LivekitIngress.IngressInfo ingressInfo_;
    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     */
    @java.lang.Override
    public boolean hasIngressInfo() {
      return ingressInfo_ != null;
    }
    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     */
    @java.lang.Override
    public livekit.LivekitIngress.IngressInfo getIngressInfo() {
      return ingressInfo_ == null ? livekit.LivekitIngress.IngressInfo.getDefaultInstance() : ingressInfo_;
    }
    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     */
    private void setIngressInfo(livekit.LivekitIngress.IngressInfo value) {
      value.getClass();
  ingressInfo_ = value;

      }
    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeIngressInfo(livekit.LivekitIngress.IngressInfo value) {
      value.getClass();
  if (ingressInfo_ != null &&
          ingressInfo_ != livekit.LivekitIngress.IngressInfo.getDefaultInstance()) {
        ingressInfo_ =
          livekit.LivekitIngress.IngressInfo.newBuilder(ingressInfo_).mergeFrom(value).buildPartial();
      } else {
        ingressInfo_ = value;
      }

    }
    /**
     * <pre>
     * set when event is ingress_*
     * </pre>
     *
     * <code>.livekit.IngressInfo ingress_info = 10;</code>
     */
    private void clearIngressInfo() {  ingressInfo_ = null;

    }

    public static final int TRACK_FIELD_NUMBER = 8;
    private livekit.LivekitModels.TrackInfo track_;
    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     */
    @java.lang.Override
    public boolean hasTrack() {
      return track_ != null;
    }
    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     */
    @java.lang.Override
    public livekit.LivekitModels.TrackInfo getTrack() {
      return track_ == null ? livekit.LivekitModels.TrackInfo.getDefaultInstance() : track_;
    }
    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     */
    private void setTrack(livekit.LivekitModels.TrackInfo value) {
      value.getClass();
  track_ = value;

      }
    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeTrack(livekit.LivekitModels.TrackInfo value) {
      value.getClass();
  if (track_ != null &&
          track_ != livekit.LivekitModels.TrackInfo.getDefaultInstance()) {
        track_ =
          livekit.LivekitModels.TrackInfo.newBuilder(track_).mergeFrom(value).buildPartial();
      } else {
        track_ = value;
      }

    }
    /**
     * <pre>
     * set when event is track_*
     * </pre>
     *
     * <code>.livekit.TrackInfo track = 8;</code>
     */
    private void clearTrack() {  track_ = null;

    }

    public static final int ID_FIELD_NUMBER = 6;
    private java.lang.String id_;
    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return id_;
    }
    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(id_);
    }
    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     * @param value The id to set.
     */
    private void setId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      id_ = value;
    }
    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     */
    private void clearId() {

      id_ = getDefaultInstance().getId();
    }
    /**
     * <pre>
     * unique event uuid
     * </pre>
     *
     * <code>string id = 6;</code>
     * @param value The bytes for id to set.
     */
    private void setIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      id_ = value.toStringUtf8();

    }

    public static final int CREATED_AT_FIELD_NUMBER = 7;
    private long createdAt_;
    /**
     * <pre>
     * timestamp in seconds
     * </pre>
     *
     * <code>int64 created_at = 7;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <pre>
     * timestamp in seconds
     * </pre>
     *
     * <code>int64 created_at = 7;</code>
     * @param value The createdAt to set.
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <pre>
     * timestamp in seconds
     * </pre>
     *
     * <code>int64 created_at = 7;</code>
     */
    private void clearCreatedAt() {

      createdAt_ = 0L;
    }

    public static final int NUM_DROPPED_FIELD_NUMBER = 11;
    private int numDropped_;
    /**
     * <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
     *     See livekit_webhook.proto;l=51
     * @return The numDropped.
     */
    @java.lang.Override
    @java.lang.Deprecated public int getNumDropped() {
      return numDropped_;
    }
    /**
     * <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
     *     See livekit_webhook.proto;l=51
     * @param value The numDropped to set.
     */
    private void setNumDropped(int value) {
      
      numDropped_ = value;
    }
    /**
     * <code>int32 num_dropped = 11 [deprecated = true];</code>
     * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
     *     See livekit_webhook.proto;l=51
     */
    private void clearNumDropped() {

      numDropped_ = 0;
    }

    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static livekit.LivekitWebhook.WebhookEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(livekit.LivekitWebhook.WebhookEvent prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code livekit.WebhookEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          livekit.LivekitWebhook.WebhookEvent, Builder> implements
        // @@protoc_insertion_point(builder_implements:livekit.WebhookEvent)
        livekit.LivekitWebhook.WebhookEventOrBuilder {
      // Construct using livekit.LivekitWebhook.WebhookEvent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
       * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
       * ingress_started, ingress_ended
       * </pre>
       *
       * <code>string event = 1;</code>
       * @return The event.
       */
      @java.lang.Override
      public java.lang.String getEvent() {
        return instance.getEvent();
      }
      /**
       * <pre>
       * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
       * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
       * ingress_started, ingress_ended
       * </pre>
       *
       * <code>string event = 1;</code>
       * @return The bytes for event.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEventBytes() {
        return instance.getEventBytes();
      }
      /**
       * <pre>
       * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
       * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
       * ingress_started, ingress_ended
       * </pre>
       *
       * <code>string event = 1;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(
          java.lang.String value) {
        copyOnWrite();
        instance.setEvent(value);
        return this;
      }
      /**
       * <pre>
       * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
       * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
       * ingress_started, ingress_ended
       * </pre>
       *
       * <code>string event = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        copyOnWrite();
        instance.clearEvent();
        return this;
      }
      /**
       * <pre>
       * one of room_started, room_finished, participant_joined, participant_left, participant_connection_aborted,
       * track_published, track_unpublished, egress_started, egress_updated, egress_ended,
       * ingress_started, ingress_ended
       * </pre>
       *
       * <code>string event = 1;</code>
       * @param value The bytes for event to set.
       * @return This builder for chaining.
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEventBytes(value);
        return this;
      }

      /**
       * <code>.livekit.Room room = 2;</code>
       */
      @java.lang.Override
      public boolean hasRoom() {
        return instance.hasRoom();
      }
      /**
       * <code>.livekit.Room room = 2;</code>
       */
      @java.lang.Override
      public livekit.LivekitModels.Room getRoom() {
        return instance.getRoom();
      }
      /**
       * <code>.livekit.Room room = 2;</code>
       */
      public Builder setRoom(livekit.LivekitModels.Room value) {
        copyOnWrite();
        instance.setRoom(value);
        return this;
        }
      /**
       * <code>.livekit.Room room = 2;</code>
       */
      public Builder setRoom(
          livekit.LivekitModels.Room.Builder builderForValue) {
        copyOnWrite();
        instance.setRoom(builderForValue.build());
        return this;
      }
      /**
       * <code>.livekit.Room room = 2;</code>
       */
      public Builder mergeRoom(livekit.LivekitModels.Room value) {
        copyOnWrite();
        instance.mergeRoom(value);
        return this;
      }
      /**
       * <code>.livekit.Room room = 2;</code>
       */
      public Builder clearRoom() {  copyOnWrite();
        instance.clearRoom();
        return this;
      }

      /**
       * <pre>
       * set when event is participant_* or track_*
       * </pre>
       *
       * <code>.livekit.ParticipantInfo participant = 3;</code>
       */
      @java.lang.Override
      public boolean hasParticipant() {
        return instance.hasParticipant();
      }
      /**
       * <pre>
       * set when event is participant_* or track_*
       * </pre>
       *
       * <code>.livekit.ParticipantInfo participant = 3;</code>
       */
      @java.lang.Override
      public livekit.LivekitModels.ParticipantInfo getParticipant() {
        return instance.getParticipant();
      }
      /**
       * <pre>
       * set when event is participant_* or track_*
       * </pre>
       *
       * <code>.livekit.ParticipantInfo participant = 3;</code>
       */
      public Builder setParticipant(livekit.LivekitModels.ParticipantInfo value) {
        copyOnWrite();
        instance.setParticipant(value);
        return this;
        }
      /**
       * <pre>
       * set when event is participant_* or track_*
       * </pre>
       *
       * <code>.livekit.ParticipantInfo participant = 3;</code>
       */
      public Builder setParticipant(
          livekit.LivekitModels.ParticipantInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setParticipant(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * set when event is participant_* or track_*
       * </pre>
       *
       * <code>.livekit.ParticipantInfo participant = 3;</code>
       */
      public Builder mergeParticipant(livekit.LivekitModels.ParticipantInfo value) {
        copyOnWrite();
        instance.mergeParticipant(value);
        return this;
      }
      /**
       * <pre>
       * set when event is participant_* or track_*
       * </pre>
       *
       * <code>.livekit.ParticipantInfo participant = 3;</code>
       */
      public Builder clearParticipant() {  copyOnWrite();
        instance.clearParticipant();
        return this;
      }

      /**
       * <pre>
       * set when event is egress_*
       * </pre>
       *
       * <code>.livekit.EgressInfo egress_info = 9;</code>
       */
      @java.lang.Override
      public boolean hasEgressInfo() {
        return instance.hasEgressInfo();
      }
      /**
       * <pre>
       * set when event is egress_*
       * </pre>
       *
       * <code>.livekit.EgressInfo egress_info = 9;</code>
       */
      @java.lang.Override
      public livekit.LivekitEgress.EgressInfo getEgressInfo() {
        return instance.getEgressInfo();
      }
      /**
       * <pre>
       * set when event is egress_*
       * </pre>
       *
       * <code>.livekit.EgressInfo egress_info = 9;</code>
       */
      public Builder setEgressInfo(livekit.LivekitEgress.EgressInfo value) {
        copyOnWrite();
        instance.setEgressInfo(value);
        return this;
        }
      /**
       * <pre>
       * set when event is egress_*
       * </pre>
       *
       * <code>.livekit.EgressInfo egress_info = 9;</code>
       */
      public Builder setEgressInfo(
          livekit.LivekitEgress.EgressInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setEgressInfo(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * set when event is egress_*
       * </pre>
       *
       * <code>.livekit.EgressInfo egress_info = 9;</code>
       */
      public Builder mergeEgressInfo(livekit.LivekitEgress.EgressInfo value) {
        copyOnWrite();
        instance.mergeEgressInfo(value);
        return this;
      }
      /**
       * <pre>
       * set when event is egress_*
       * </pre>
       *
       * <code>.livekit.EgressInfo egress_info = 9;</code>
       */
      public Builder clearEgressInfo() {  copyOnWrite();
        instance.clearEgressInfo();
        return this;
      }

      /**
       * <pre>
       * set when event is ingress_*
       * </pre>
       *
       * <code>.livekit.IngressInfo ingress_info = 10;</code>
       */
      @java.lang.Override
      public boolean hasIngressInfo() {
        return instance.hasIngressInfo();
      }
      /**
       * <pre>
       * set when event is ingress_*
       * </pre>
       *
       * <code>.livekit.IngressInfo ingress_info = 10;</code>
       */
      @java.lang.Override
      public livekit.LivekitIngress.IngressInfo getIngressInfo() {
        return instance.getIngressInfo();
      }
      /**
       * <pre>
       * set when event is ingress_*
       * </pre>
       *
       * <code>.livekit.IngressInfo ingress_info = 10;</code>
       */
      public Builder setIngressInfo(livekit.LivekitIngress.IngressInfo value) {
        copyOnWrite();
        instance.setIngressInfo(value);
        return this;
        }
      /**
       * <pre>
       * set when event is ingress_*
       * </pre>
       *
       * <code>.livekit.IngressInfo ingress_info = 10;</code>
       */
      public Builder setIngressInfo(
          livekit.LivekitIngress.IngressInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setIngressInfo(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * set when event is ingress_*
       * </pre>
       *
       * <code>.livekit.IngressInfo ingress_info = 10;</code>
       */
      public Builder mergeIngressInfo(livekit.LivekitIngress.IngressInfo value) {
        copyOnWrite();
        instance.mergeIngressInfo(value);
        return this;
      }
      /**
       * <pre>
       * set when event is ingress_*
       * </pre>
       *
       * <code>.livekit.IngressInfo ingress_info = 10;</code>
       */
      public Builder clearIngressInfo() {  copyOnWrite();
        instance.clearIngressInfo();
        return this;
      }

      /**
       * <pre>
       * set when event is track_*
       * </pre>
       *
       * <code>.livekit.TrackInfo track = 8;</code>
       */
      @java.lang.Override
      public boolean hasTrack() {
        return instance.hasTrack();
      }
      /**
       * <pre>
       * set when event is track_*
       * </pre>
       *
       * <code>.livekit.TrackInfo track = 8;</code>
       */
      @java.lang.Override
      public livekit.LivekitModels.TrackInfo getTrack() {
        return instance.getTrack();
      }
      /**
       * <pre>
       * set when event is track_*
       * </pre>
       *
       * <code>.livekit.TrackInfo track = 8;</code>
       */
      public Builder setTrack(livekit.LivekitModels.TrackInfo value) {
        copyOnWrite();
        instance.setTrack(value);
        return this;
        }
      /**
       * <pre>
       * set when event is track_*
       * </pre>
       *
       * <code>.livekit.TrackInfo track = 8;</code>
       */
      public Builder setTrack(
          livekit.LivekitModels.TrackInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setTrack(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * set when event is track_*
       * </pre>
       *
       * <code>.livekit.TrackInfo track = 8;</code>
       */
      public Builder mergeTrack(livekit.LivekitModels.TrackInfo value) {
        copyOnWrite();
        instance.mergeTrack(value);
        return this;
      }
      /**
       * <pre>
       * set when event is track_*
       * </pre>
       *
       * <code>.livekit.TrackInfo track = 8;</code>
       */
      public Builder clearTrack() {  copyOnWrite();
        instance.clearTrack();
        return this;
      }

      /**
       * <pre>
       * unique event uuid
       * </pre>
       *
       * <code>string id = 6;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        return instance.getId();
      }
      /**
       * <pre>
       * unique event uuid
       * </pre>
       *
       * <code>string id = 6;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        return instance.getIdBytes();
      }
      /**
       * <pre>
       * unique event uuid
       * </pre>
       *
       * <code>string id = 6;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <pre>
       * unique event uuid
       * </pre>
       *
       * <code>string id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }
      /**
       * <pre>
       * unique event uuid
       * </pre>
       *
       * <code>string id = 6;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * timestamp in seconds
       * </pre>
       *
       * <code>int64 created_at = 7;</code>
       * @return The createdAt.
       */
      @java.lang.Override
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <pre>
       * timestamp in seconds
       * </pre>
       *
       * <code>int64 created_at = 7;</code>
       * @param value The createdAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <pre>
       * timestamp in seconds
       * </pre>
       *
       * <code>int64 created_at = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>int32 num_dropped = 11 [deprecated = true];</code>
       * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
       *     See livekit_webhook.proto;l=51
       * @return The numDropped.
       */
      @java.lang.Override
      @java.lang.Deprecated public int getNumDropped() {
        return instance.getNumDropped();
      }
      /**
       * <code>int32 num_dropped = 11 [deprecated = true];</code>
       * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
       *     See livekit_webhook.proto;l=51
       * @param value The numDropped to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setNumDropped(int value) {
        copyOnWrite();
        instance.setNumDropped(value);
        return this;
      }
      /**
       * <code>int32 num_dropped = 11 [deprecated = true];</code>
       * @deprecated livekit.WebhookEvent.num_dropped is deprecated.
       *     See livekit_webhook.proto;l=51
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearNumDropped() {
        copyOnWrite();
        instance.clearNumDropped();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:livekit.WebhookEvent)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new livekit.LivekitWebhook.WebhookEvent();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "event_",
              "room_",
              "participant_",
              "id_",
              "createdAt_",
              "track_",
              "egressInfo_",
              "ingressInfo_",
              "numDropped_",
            };
            java.lang.String info =
                "\u0000\t\u0000\u0000\u0001\u000b\t\u0000\u0000\u0000\u0001\u0208\u0002\t\u0003\t" +
                "\u0006\u0208\u0007\u0002\b\t\t\t\n\t\u000b\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<livekit.LivekitWebhook.WebhookEvent> parser = PARSER;
          if (parser == null) {
            synchronized (livekit.LivekitWebhook.WebhookEvent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<livekit.LivekitWebhook.WebhookEvent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:livekit.WebhookEvent)
    private static final livekit.LivekitWebhook.WebhookEvent DEFAULT_INSTANCE;
    static {
      WebhookEvent defaultInstance = new WebhookEvent();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WebhookEvent.class, defaultInstance);
    }

    public static livekit.LivekitWebhook.WebhookEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WebhookEvent> PARSER;

    public static com.google.protobuf.Parser<WebhookEvent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
