// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.AudioType;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AudioHandlerModule_AudioOutputTypeFactory implements Factory<AudioType> {
  private final Provider<AudioType> audioOutputOverrideProvider;

  public AudioHandlerModule_AudioOutputTypeFactory(
      Provider<AudioType> audioOutputOverrideProvider) {
    this.audioOutputOverrideProvider = audioOutputOverrideProvider;
  }

  @Override
  public AudioType get() {
    return audioOutputType(audioOutputOverrideProvider.get());
  }

  public static AudioHandlerModule_AudioOutputTypeFactory create(
      Provider<AudioType> audioOutputOverrideProvider) {
    return new AudioHandlerModule_AudioOutputTypeFactory(audioOutputOverrideProvider);
  }

  public static AudioType audioOutputType(AudioType audioOutputOverride) {
    return Preconditions.checkNotNullFromProvides(AudioHandlerModule.INSTANCE.audioOutputType(audioOutputOverride));
  }
}
