// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.media.AudioAttributes;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.AudioType;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AudioHandlerModule_AudioOutputAttributesFactory implements Factory<AudioAttributes> {
  private final Provider<AudioType> audioTypeProvider;

  public AudioHandlerModule_AudioOutputAttributesFactory(Provider<AudioType> audioTypeProvider) {
    this.audioTypeProvider = audioTypeProvider;
  }

  @Override
  public AudioAttributes get() {
    return audioOutputAttributes(audioTypeProvider.get());
  }

  public static AudioHandlerModule_AudioOutputAttributesFactory create(
      Provider<AudioType> audioTypeProvider) {
    return new AudioHandlerModule_AudioOutputAttributesFactory(audioTypeProvider);
  }

  public static AudioAttributes audioOutputAttributes(AudioType audioType) {
    return Preconditions.checkNotNullFromProvides(AudioHandlerModule.INSTANCE.audioOutputAttributes(audioType));
  }
}
