// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.AudioType;
import io.livekit.android.audio.CommunicationWorkaround;
import io.livekit.android.audio.CommunicationWorkaroundImpl;
import io.livekit.android.memory.CloseableManager;
import javax.inject.Provider;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AudioHandlerModule_CommunicationWorkaroundFactory implements Factory<CommunicationWorkaround> {
  private final Provider<Boolean> disableCommunicationWorkaroundProvider;

  private final Provider<AudioType> audioTypeProvider;

  private final Provider<CloseableManager> closeableManagerProvider;

  private final Provider<CommunicationWorkaroundImpl> commWorkaroundImplProvider;

  public AudioHandlerModule_CommunicationWorkaroundFactory(
      Provider<Boolean> disableCommunicationWorkaroundProvider,
      Provider<AudioType> audioTypeProvider, Provider<CloseableManager> closeableManagerProvider,
      Provider<CommunicationWorkaroundImpl> commWorkaroundImplProvider) {
    this.disableCommunicationWorkaroundProvider = disableCommunicationWorkaroundProvider;
    this.audioTypeProvider = audioTypeProvider;
    this.closeableManagerProvider = closeableManagerProvider;
    this.commWorkaroundImplProvider = commWorkaroundImplProvider;
  }

  @Override
  public CommunicationWorkaround get() {
    return communicationWorkaround(disableCommunicationWorkaroundProvider.get(), audioTypeProvider.get(), closeableManagerProvider.get(), commWorkaroundImplProvider);
  }

  public static AudioHandlerModule_CommunicationWorkaroundFactory create(
      Provider<Boolean> disableCommunicationWorkaroundProvider,
      Provider<AudioType> audioTypeProvider, Provider<CloseableManager> closeableManagerProvider,
      Provider<CommunicationWorkaroundImpl> commWorkaroundImplProvider) {
    return new AudioHandlerModule_CommunicationWorkaroundFactory(disableCommunicationWorkaroundProvider, audioTypeProvider, closeableManagerProvider, commWorkaroundImplProvider);
  }

  public static CommunicationWorkaround communicationWorkaround(
      boolean disableCommunicationWorkaround, AudioType audioType,
      CloseableManager closeableManager,
      Provider<CommunicationWorkaroundImpl> commWorkaroundImplProvider) {
    return Preconditions.checkNotNullFromProvides(AudioHandlerModule.INSTANCE.communicationWorkaround(disableCommunicationWorkaround, audioType, closeableManager, commWorkaroundImplProvider));
  }
}
