// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.AudioType;
import io.livekit.android.audio.AudioHandler;
import io.livekit.android.audio.AudioSwitchHandler;
import javax.inject.Provider;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AudioHandlerModule_AudioHandlerFactory implements Factory<AudioHandler> {
  private final Provider<AudioSwitchHandler> audioSwitchHandlerProvider;

  private final Provider<AudioHandler> audioHandlerOverrideProvider;

  private final Provider<AudioType> audioOutputTypeProvider;

  public AudioHandlerModule_AudioHandlerFactory(
      Provider<AudioSwitchHandler> audioSwitchHandlerProvider,
      Provider<AudioHandler> audioHandlerOverrideProvider,
      Provider<AudioType> audioOutputTypeProvider) {
    this.audioSwitchHandlerProvider = audioSwitchHandlerProvider;
    this.audioHandlerOverrideProvider = audioHandlerOverrideProvider;
    this.audioOutputTypeProvider = audioOutputTypeProvider;
  }

  @Override
  public AudioHandler get() {
    return audioHandler(audioSwitchHandlerProvider, audioHandlerOverrideProvider.get(), audioOutputTypeProvider.get());
  }

  public static AudioHandlerModule_AudioHandlerFactory create(
      Provider<AudioSwitchHandler> audioSwitchHandlerProvider,
      Provider<AudioHandler> audioHandlerOverrideProvider,
      Provider<AudioType> audioOutputTypeProvider) {
    return new AudioHandlerModule_AudioHandlerFactory(audioSwitchHandlerProvider, audioHandlerOverrideProvider, audioOutputTypeProvider);
  }

  public static AudioHandler audioHandler(Provider<AudioSwitchHandler> audioSwitchHandler,
      AudioHandler audioHandlerOverride, AudioType audioOutputType) {
    return Preconditions.checkNotNullFromProvides(AudioHandlerModule.INSTANCE.audioHandler(audioSwitchHandler, audioHandlerOverride, audioOutputType));
  }
}
