// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import kotlinx.coroutines.CoroutineDispatcher;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class CoroutinesModule_DefaultDispatcherFactory implements Factory<CoroutineDispatcher> {
  @Override
  public CoroutineDispatcher get() {
    return defaultDispatcher();
  }

  public static CoroutinesModule_DefaultDispatcherFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static CoroutineDispatcher defaultDispatcher() {
    return Preconditions.checkNotNullFromProvides(CoroutinesModule.INSTANCE.defaultDispatcher());
  }

  private static final class InstanceHolder {
    private static final CoroutinesModule_DefaultDispatcherFactory INSTANCE = new CoroutinesModule_DefaultDispatcherFactory();
  }
}
