// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import kotlinx.coroutines.MainCoroutineDispatcher;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class CoroutinesModule_MainDispatcherFactory implements Factory<MainCoroutineDispatcher> {
  @Override
  public MainCoroutineDispatcher get() {
    return mainDispatcher();
  }

  public static CoroutinesModule_MainDispatcherFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static MainCoroutineDispatcher mainDispatcher() {
    return Preconditions.checkNotNullFromProvides(CoroutinesModule.INSTANCE.mainDispatcher());
  }

  private static final class InstanceHolder {
    private static final CoroutinesModule_MainDispatcherFactory INSTANCE = new CoroutinesModule_MainDispatcherFactory();
  }
}
