// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import kotlinx.coroutines.CoroutineDispatcher;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class CoroutinesModule_UnconfinedDispatcherFactory implements Factory<CoroutineDispatcher> {
  @Override
  public CoroutineDispatcher get() {
    return unconfinedDispatcher();
  }

  public static CoroutinesModule_UnconfinedDispatcherFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static CoroutineDispatcher unconfinedDispatcher() {
    return Preconditions.checkNotNullFromProvides(CoroutinesModule.INSTANCE.unconfinedDispatcher());
  }

  private static final class InstanceHolder {
    private static final CoroutinesModule_UnconfinedDispatcherFactory INSTANCE = new CoroutinesModule_UnconfinedDispatcherFactory();
  }
}
