// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.content.Context;
import android.media.AudioAttributes;
import android.net.ConnectivityManager;
import dagger.internal.DaggerGenerated;
import dagger.internal.DelegateFactory;
import dagger.internal.DoubleCheck;
import dagger.internal.InstanceFactory;
import dagger.internal.Preconditions;
import dagger.internal.SingleCheck;
import io.livekit.android.AudioType;
import io.livekit.android.audio.AudioBufferCallbackDispatcher;
import io.livekit.android.audio.AudioHandler;
import io.livekit.android.audio.AudioProcessingController;
import io.livekit.android.audio.AudioProcessorOptions;
import io.livekit.android.audio.AudioRecordPrewarmer;
import io.livekit.android.audio.AudioRecordSamplesDispatcher;
import io.livekit.android.audio.AudioSwitchHandler;
import io.livekit.android.audio.AudioSwitchHandler_Factory;
import io.livekit.android.audio.CommunicationWorkaround;
import io.livekit.android.audio.CommunicationWorkaroundImpl;
import io.livekit.android.audio.CommunicationWorkaroundImpl_Factory;
import io.livekit.android.e2ee.E2EEManager_Factory;
import io.livekit.android.e2ee.E2EEManager_Factory_Impl;
import io.livekit.android.memory.CloseableManager;
import io.livekit.android.room.DefaultsManager;
import io.livekit.android.room.DefaultsManager_Factory;
import io.livekit.android.room.PeerConnectionTransport_Factory;
import io.livekit.android.room.PeerConnectionTransport_Factory_Impl;
import io.livekit.android.room.RTCEngine;
import io.livekit.android.room.RTCEngine_Factory;
import io.livekit.android.room.RegionUrlProvider_Factory;
import io.livekit.android.room.RegionUrlProvider_Factory_Impl;
import io.livekit.android.room.Room_Factory;
import io.livekit.android.room.Room_Factory_Impl;
import io.livekit.android.room.SignalClient;
import io.livekit.android.room.SignalClient_Factory;
import io.livekit.android.room.datastream.incoming.IncomingDataStreamManagerImpl_Factory;
import io.livekit.android.room.datastream.outgoing.OutgoingDataStreamManagerImpl;
import io.livekit.android.room.datastream.outgoing.OutgoingDataStreamManagerImpl_Factory;
import io.livekit.android.room.network.NetworkCallbackManager;
import io.livekit.android.room.network.NetworkCallbackRegistry;
import io.livekit.android.room.participant.LocalParticipant_Factory;
import io.livekit.android.room.participant.LocalParticipant_Factory_Impl;
import io.livekit.android.room.participant.RemoteParticipant_Factory;
import io.livekit.android.room.participant.RemoteParticipant_Factory_Impl;
import io.livekit.android.room.provisions.LKObjects;
import io.livekit.android.room.provisions.LKObjects_Factory;
import io.livekit.android.room.track.LocalAudioTrack_Factory;
import io.livekit.android.room.track.LocalAudioTrack_Factory_Impl;
import io.livekit.android.room.track.LocalScreencastVideoTrack_Factory;
import io.livekit.android.room.track.LocalScreencastVideoTrack_Factory_Impl;
import io.livekit.android.room.track.LocalVideoTrack_Factory;
import io.livekit.android.room.track.LocalVideoTrack_Factory_Impl;
import io.livekit.android.room.track.RemoteAudioTrack_Factory;
import io.livekit.android.room.track.RemoteAudioTrack_Factory_Impl;
import io.livekit.android.room.track.RemoteVideoTrack_Factory;
import io.livekit.android.room.track.RemoteVideoTrack_Factory_Impl;
import io.livekit.android.room.util.ConnectionWarmer;
import io.livekit.android.room.util.OkHttpConnectionWarmer;
import io.livekit.android.room.util.OkHttpConnectionWarmer_Factory;
import io.livekit.android.stats.NetworkInfo;
import io.livekit.android.webrtc.CustomAudioProcessingFactory;
import io.livekit.android.webrtc.PeerConnectionFactoryManager;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import kotlinx.serialization.json.Json;
import livekit.org.webrtc.AudioProcessingFactory;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.MediaStreamTrack;
import livekit.org.webrtc.PeerConnectionFactory;
import livekit.org.webrtc.RtpCapabilities;
import livekit.org.webrtc.VideoDecoderFactory;
import livekit.org.webrtc.VideoEncoderFactory;
import livekit.org.webrtc.audio.AudioDeviceModule;
import livekit.org.webrtc.audio.JavaAudioDeviceModule;
import okhttp3.OkHttpClient;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class DaggerLiveKitComponent {
  private DaggerLiveKitComponent() {
  }

  public static LiveKitComponent.Factory factory() {
    return new Factory();
  }

  private static final class Factory implements LiveKitComponent.Factory {
    @Override
    public LiveKitComponent create(Context appContext, OverridesModule overridesModule) {
      Preconditions.checkNotNull(appContext);
      Preconditions.checkNotNull(overridesModule);
      return new LiveKitComponentImpl(overridesModule, appContext);
    }
  }

  private static final class LiveKitComponentImpl implements LiveKitComponent {
    private final LiveKitComponentImpl liveKitComponentImpl = this;

    private Provider<OkHttpClient> okHttpClientProvider;

    private Provider<OkHttpClient> okHttpClientProvider2;

    private Provider<okhttp3.WebSocket.Factory> websocketFactoryProvider;

    private Provider<Json> kotlinSerializationJsonProvider;

    private Provider<Context> appContextProvider;

    private Provider<NetworkInfo> networkInfoProvider;

    private Provider<SignalClient> signalClientProvider;

    private Provider<LibWebrtcInitialization> libWebrtcInitializationProvider;

    private Provider<AudioDeviceModule> audioDeviceModuleProvider;

    private Provider<Function1<JavaAudioDeviceModule.Builder, Unit>> javaAudioDeviceModuleCustomizerProvider;

    private Provider<AudioType> audioOutputTypeProvider;

    private Provider<AudioType> audioOutputTypeProvider2;

    private Provider<AudioAttributes> audioOutputAttributesProvider;

    private Provider<CloseableManager> closeableManagerProvider;

    private Provider<Boolean> disableCommunicationWorkAroundProvider;

    private Provider<CommunicationWorkaroundImpl> communicationWorkaroundImplProvider;

    private Provider<CommunicationWorkaround> communicationWorkaroundProvider;

    private Provider<AudioRecordSamplesDispatcher> localAudioSamplesDispatcherProvider;

    private Provider<AudioBufferCallbackDispatcher> localAudioBufferCallbackDispatcherProvider;

    private Provider<AudioDeviceModule> audioModuleProvider;

    private Provider<EglBase> eglBaseProvider;

    private Provider<EglBase> eglBaseProvider2;

    private Provider<EglBase.Context> eglContextProvider;

    private Provider<VideoEncoderFactory> videoEncoderFactoryProvider;

    private Provider<VideoEncoderFactory> videoEncoderFactoryProvider2;

    private Provider<VideoDecoderFactory> videoDecoderFactoryProvider;

    private Provider<VideoDecoderFactory> videoDecoderFactoryProvider2;

    private Provider<PeerConnectionFactory.Options> peerConnectionFactoryOptionsProvider;

    private Provider<AudioProcessorOptions> audioProcessorOptionsProvider;

    private Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider;

    private Provider<AudioProcessingFactory> audioProcessingFactoryProvider;

    private Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider;

    private Provider<PeerConnectionFactory> peerConnectionFactoryProvider;

    private Provider<RTCThreadToken> rtcThreadTokenProvider;

    private PeerConnectionTransport_Factory peerConnectionTransportProvider;

    private Provider<io.livekit.android.room.PeerConnectionTransport.Factory> factoryProvider;

    private Provider<RTCEngine> rTCEngineProvider;

    private Provider<DefaultsManager> defaultsManagerProvider;

    private Provider<io.livekit.android.room.track.LocalVideoTrack.Factory> factoryProvider2;

    private LocalVideoTrack_Factory localVideoTrackProvider;

    private LocalScreencastVideoTrack_Factory localScreencastVideoTrackProvider;

    private Provider<io.livekit.android.room.track.LocalScreencastVideoTrack.Factory> factoryProvider3;

    private Provider<AudioProcessingController> audioProcessingControllerProvider;

    private Provider<Boolean> disableAudioPrewarmProvider;

    private Provider<AudioRecordPrewarmer> audioPrewarmerProvider;

    private LocalAudioTrack_Factory localAudioTrackProvider;

    private Provider<io.livekit.android.room.track.LocalAudioTrack.Factory> factoryProvider4;

    private Provider<Function1<MediaStreamTrack.MediaType, RtpCapabilities>> senderCapabilitiesGetterProvider;

    private Provider<OutgoingDataStreamManagerImpl> outgoingDataStreamManagerImplProvider;

    private LocalParticipant_Factory localParticipantProvider;

    private Provider<io.livekit.android.room.participant.LocalParticipant.Factory> factoryProvider5;

    private Provider<AudioSwitchHandler> audioSwitchHandlerProvider;

    private Provider<AudioHandler> audioHandlerProvider;

    private Provider<AudioHandler> audioHandlerProvider2;

    private E2EEManager_Factory e2EEManagerProvider;

    private Provider<io.livekit.android.e2ee.E2EEManager.Factory> factoryProvider6;

    private Provider<LKObjects> lKObjectsProvider;

    private Provider<ConnectivityManager> connectivityManagerProvider;

    private Provider<NetworkCallbackRegistry> networkCallbackRegistrarProvider;

    private Provider<Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager>> networkCallbackManagerFactoryProvider;

    private RegionUrlProvider_Factory regionUrlProvider;

    private Provider<io.livekit.android.room.RegionUrlProvider.Factory> factoryProvider7;

    private Provider<OkHttpConnectionWarmer> okHttpConnectionWarmerProvider;

    private Provider<ConnectionWarmer> connectionWarmerProvider;

    private RemoteAudioTrack_Factory remoteAudioTrackProvider;

    private Provider<io.livekit.android.room.track.RemoteAudioTrack.Factory> factoryProvider8;

    private RemoteVideoTrack_Factory remoteVideoTrackProvider;

    private Provider<io.livekit.android.room.track.RemoteVideoTrack.Factory> factoryProvider9;

    private RemoteParticipant_Factory remoteParticipantProvider;

    private Provider<io.livekit.android.room.participant.RemoteParticipant.Factory> factoryProvider10;

    private Room_Factory roomProvider;

    private Provider<io.livekit.android.room.Room.Factory> factoryProvider11;

    private LiveKitComponentImpl(OverridesModule overridesModuleParam, Context appContextParam) {

      initialize(overridesModuleParam, appContextParam);

    }

    @SuppressWarnings("unchecked")
    private void initialize(final OverridesModule overridesModuleParam,
        final Context appContextParam) {
      this.okHttpClientProvider = OverridesModule_OkHttpClientFactory.create(overridesModuleParam);
      this.okHttpClientProvider2 = DoubleCheck.provider(WebModule_OkHttpClientFactory.create(okHttpClientProvider));
      this.websocketFactoryProvider = WebModule_WebsocketFactoryFactory.create(okHttpClientProvider2);
      this.kotlinSerializationJsonProvider = SingleCheck.provider(JsonFormatModule_KotlinSerializationJsonFactory.create());
      this.appContextProvider = InstanceFactory.create(appContextParam);
      this.networkInfoProvider = SingleCheck.provider(WebModule_NetworkInfoFactory.create(appContextProvider));
      this.signalClientProvider = DoubleCheck.provider(SignalClient_Factory.create(websocketFactoryProvider, kotlinSerializationJsonProvider, okHttpClientProvider2, CoroutinesModule_IoDispatcherFactory.create(), networkInfoProvider));
      this.libWebrtcInitializationProvider = DoubleCheck.provider(RTCModule_LibWebrtcInitializationFactory.create(appContextProvider));
      this.audioDeviceModuleProvider = OverridesModule_AudioDeviceModuleFactory.create(overridesModuleParam);
      this.javaAudioDeviceModuleCustomizerProvider = OverridesModule_JavaAudioDeviceModuleCustomizerFactory.create(overridesModuleParam);
      this.audioOutputTypeProvider = OverridesModule_AudioOutputTypeFactory.create(overridesModuleParam);
      this.audioOutputTypeProvider2 = AudioHandlerModule_AudioOutputTypeFactory.create(audioOutputTypeProvider);
      this.audioOutputAttributesProvider = AudioHandlerModule_AudioOutputAttributesFactory.create(audioOutputTypeProvider2);
      this.closeableManagerProvider = DoubleCheck.provider(MemoryModule_CloseableManagerFactory.create());
      this.disableCommunicationWorkAroundProvider = OverridesModule_DisableCommunicationWorkAroundFactory.create(overridesModuleParam);
      this.communicationWorkaroundImplProvider = DoubleCheck.provider(CommunicationWorkaroundImpl_Factory.create(appContextProvider, CoroutinesModule_IoDispatcherFactory.create()));
      this.communicationWorkaroundProvider = DoubleCheck.provider(AudioHandlerModule_CommunicationWorkaroundFactory.create(disableCommunicationWorkAroundProvider, audioOutputTypeProvider2, closeableManagerProvider, communicationWorkaroundImplProvider));
      this.localAudioSamplesDispatcherProvider = DoubleCheck.provider(RTCModule_LocalAudioSamplesDispatcherFactory.create());
      this.localAudioBufferCallbackDispatcherProvider = DoubleCheck.provider(RTCModule_LocalAudioBufferCallbackDispatcherFactory.create());
      this.audioModuleProvider = DoubleCheck.provider(RTCModule_AudioModuleFactory.create(audioDeviceModuleProvider, javaAudioDeviceModuleCustomizerProvider, audioOutputAttributesProvider, appContextProvider, closeableManagerProvider, communicationWorkaroundProvider, localAudioSamplesDispatcherProvider, localAudioBufferCallbackDispatcherProvider));
      this.eglBaseProvider = OverridesModule_EglBaseFactory.create(overridesModuleParam);
      this.eglBaseProvider2 = DoubleCheck.provider(RTCModule_EglBaseFactory.create(eglBaseProvider, closeableManagerProvider));
      this.eglContextProvider = RTCModule_EglContextFactory.create(eglBaseProvider2);
      this.videoEncoderFactoryProvider = OverridesModule_VideoEncoderFactoryFactory.create(overridesModuleParam);
      this.videoEncoderFactoryProvider2 = RTCModule_VideoEncoderFactoryFactory.create(libWebrtcInitializationProvider, RTCModule_VideoHwAccelFactory.create(), eglContextProvider, videoEncoderFactoryProvider);
      this.videoDecoderFactoryProvider = OverridesModule_VideoDecoderFactoryFactory.create(overridesModuleParam);
      this.videoDecoderFactoryProvider2 = RTCModule_VideoDecoderFactoryFactory.create(libWebrtcInitializationProvider, RTCModule_VideoHwAccelFactory.create(), eglContextProvider, videoDecoderFactoryProvider);
      this.peerConnectionFactoryOptionsProvider = OverridesModule_PeerConnectionFactoryOptionsFactory.create(overridesModuleParam);
      this.audioProcessorOptionsProvider = OverridesModule_AudioProcessorOptionsFactory.create(overridesModuleParam);
      this.customAudioProcessingFactoryProvider = DoubleCheck.provider(RTCModule_CustomAudioProcessingFactoryFactory.create(libWebrtcInitializationProvider, audioProcessorOptionsProvider));
      this.audioProcessingFactoryProvider = RTCModule_AudioProcessingFactoryFactory.create(customAudioProcessingFactoryProvider);
      this.peerConnectionFactoryManagerProvider = DoubleCheck.provider(RTCModule_PeerConnectionFactoryManagerFactory.create(libWebrtcInitializationProvider, audioModuleProvider, videoEncoderFactoryProvider2, videoDecoderFactoryProvider2, peerConnectionFactoryOptionsProvider, closeableManagerProvider, audioProcessingFactoryProvider));
      this.peerConnectionFactoryProvider = DoubleCheck.provider(RTCModule_PeerConnectionFactoryFactory.create(peerConnectionFactoryManagerProvider));
      this.rtcThreadTokenProvider = SingleCheck.provider(RTCModule_RtcThreadTokenFactory.create(peerConnectionFactoryManagerProvider));
      this.peerConnectionTransportProvider = PeerConnectionTransport_Factory.create(CoroutinesModule_IoDispatcherFactory.create(), peerConnectionFactoryProvider, RTCModule_SdpFactoryFactory.create(), rtcThreadTokenProvider);
      this.factoryProvider = PeerConnectionTransport_Factory_Impl.create(peerConnectionTransportProvider);
      this.rTCEngineProvider = DoubleCheck.provider(RTCEngine_Factory.create(signalClientProvider, factoryProvider, CoroutinesModule_IoDispatcherFactory.create(), rtcThreadTokenProvider, RTCModule_DataPacketCryptorManagerFactoryFactory.create()));
      this.defaultsManagerProvider = DoubleCheck.provider(DefaultsManager_Factory.create());
      this.factoryProvider2 = new DelegateFactory<>();
      this.localVideoTrackProvider = LocalVideoTrack_Factory.create(peerConnectionFactoryProvider, appContextProvider, eglBaseProvider2, defaultsManagerProvider, factoryProvider2, rtcThreadTokenProvider);
      DelegateFactory.setDelegate(factoryProvider2, LocalVideoTrack_Factory_Impl.create(localVideoTrackProvider));
      this.localScreencastVideoTrackProvider = LocalScreencastVideoTrack_Factory.create(peerConnectionFactoryProvider, appContextProvider, eglBaseProvider2, defaultsManagerProvider, factoryProvider2, rtcThreadTokenProvider);
      this.factoryProvider3 = LocalScreencastVideoTrack_Factory_Impl.create(localScreencastVideoTrackProvider);
      this.audioProcessingControllerProvider = RTCModule_AudioProcessingControllerFactory.create(customAudioProcessingFactoryProvider);
      this.disableAudioPrewarmProvider = OverridesModule_DisableAudioPrewarmFactory.create(overridesModuleParam);
      this.audioPrewarmerProvider = RTCModule_AudioPrewarmerFactory.create(disableAudioPrewarmProvider, audioModuleProvider);
      this.localAudioTrackProvider = LocalAudioTrack_Factory.create(audioProcessingControllerProvider, CoroutinesModule_DefaultDispatcherFactory.create(), localAudioSamplesDispatcherProvider, localAudioBufferCallbackDispatcherProvider, audioPrewarmerProvider, rtcThreadTokenProvider);
      this.factoryProvider4 = LocalAudioTrack_Factory_Impl.create(localAudioTrackProvider);
      this.senderCapabilitiesGetterProvider = RTCModule_SenderCapabilitiesGetterFactory.create(peerConnectionFactoryProvider);
      this.outgoingDataStreamManagerImplProvider = OutgoingDataStreamManagerImpl_Factory.create(rTCEngineProvider);
      this.localParticipantProvider = LocalParticipant_Factory.create(rTCEngineProvider, peerConnectionFactoryProvider, appContextProvider, eglBaseProvider2, factoryProvider3, factoryProvider2, factoryProvider4, defaultsManagerProvider, CoroutinesModule_DefaultDispatcherFactory.create(), senderCapabilitiesGetterProvider, ((Provider) outgoingDataStreamManagerImplProvider));
      this.factoryProvider5 = LocalParticipant_Factory_Impl.create(localParticipantProvider);
      this.audioSwitchHandlerProvider = DoubleCheck.provider(AudioSwitchHandler_Factory.create(appContextProvider));
      this.audioHandlerProvider = OverridesModule_AudioHandlerFactory.create(overridesModuleParam);
      this.audioHandlerProvider2 = DoubleCheck.provider(AudioHandlerModule_AudioHandlerFactory.create(audioSwitchHandlerProvider, audioHandlerProvider, audioOutputTypeProvider2));
      this.e2EEManagerProvider = E2EEManager_Factory.create(peerConnectionFactoryProvider, RTCModule_DataPacketCryptorManagerFactoryFactory.create());
      this.factoryProvider6 = E2EEManager_Factory_Impl.create(e2EEManagerProvider);
      this.lKObjectsProvider = LKObjects_Factory.create(eglBaseProvider2, audioModuleProvider);
      this.connectivityManagerProvider = WebModule_ConnectivityManagerFactory.create(appContextProvider);
      this.networkCallbackRegistrarProvider = WebModule_NetworkCallbackRegistrarFactory.create(connectivityManagerProvider);
      this.networkCallbackManagerFactoryProvider = SingleCheck.provider(WebModule_NetworkCallbackManagerFactoryFactory.create(closeableManagerProvider, networkCallbackRegistrarProvider));
      this.regionUrlProvider = RegionUrlProvider_Factory.create(okHttpClientProvider2, kotlinSerializationJsonProvider);
      this.factoryProvider7 = RegionUrlProvider_Factory_Impl.create(regionUrlProvider);
      this.okHttpConnectionWarmerProvider = OkHttpConnectionWarmer_Factory.create(okHttpClientProvider2);
      this.connectionWarmerProvider = WebModule_ConnectionWarmerFactory.create(okHttpConnectionWarmerProvider);
      this.remoteAudioTrackProvider = RemoteAudioTrack_Factory.create(rtcThreadTokenProvider);
      this.factoryProvider8 = RemoteAudioTrack_Factory_Impl.create(remoteAudioTrackProvider);
      this.remoteVideoTrackProvider = RemoteVideoTrack_Factory.create(CoroutinesModule_DefaultDispatcherFactory.create(), rtcThreadTokenProvider);
      this.factoryProvider9 = RemoteVideoTrack_Factory_Impl.create(remoteVideoTrackProvider);
      this.remoteParticipantProvider = RemoteParticipant_Factory.create(signalClientProvider, CoroutinesModule_IoDispatcherFactory.create(), CoroutinesModule_DefaultDispatcherFactory.create(), factoryProvider8, factoryProvider9);
      this.factoryProvider10 = RemoteParticipant_Factory_Impl.create(remoteParticipantProvider);
      this.roomProvider = Room_Factory.create(rTCEngineProvider, eglBaseProvider2, factoryProvider5, defaultsManagerProvider, CoroutinesModule_DefaultDispatcherFactory.create(), CoroutinesModule_IoDispatcherFactory.create(), audioHandlerProvider2, closeableManagerProvider, factoryProvider6, communicationWorkaroundProvider, audioProcessingControllerProvider, lKObjectsProvider, networkCallbackManagerFactoryProvider, audioModuleProvider, factoryProvider7, connectionWarmerProvider, audioPrewarmerProvider, ((Provider) IncomingDataStreamManagerImpl_Factory.create()), factoryProvider10);
      this.factoryProvider11 = Room_Factory_Impl.create(roomProvider);
    }

    @Override
    public io.livekit.android.room.Room.Factory roomFactory() {
      return factoryProvider11.get();
    }

    @Override
    public PeerConnectionFactory peerConnectionFactory() {
      return peerConnectionFactoryProvider.get();
    }

    @Override
    public EglBase eglBase() {
      return eglBaseProvider2.get();
    }
  }
}
