// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import kotlinx.serialization.json.Json;

@ScopeMetadata("dagger.Reusable")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class JsonFormatModule_KotlinSerializationJsonFactory implements Factory<Json> {
  @Override
  public Json get() {
    return kotlinSerializationJson();
  }

  public static JsonFormatModule_KotlinSerializationJsonFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static Json kotlinSerializationJson() {
    return Preconditions.checkNotNullFromProvides(JsonFormatModule.INSTANCE.kotlinSerializationJson());
  }

  private static final class InstanceHolder {
    private static final JsonFormatModule_KotlinSerializationJsonFactory INSTANCE = new JsonFormatModule_KotlinSerializationJsonFactory();
  }
}
