// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.memory.CloseableManager;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class MemoryModule_CloseableManagerFactory implements Factory<CloseableManager> {
  @Override
  public CloseableManager get() {
    return closeableManager();
  }

  public static MemoryModule_CloseableManagerFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static CloseableManager closeableManager() {
    return Preconditions.checkNotNullFromProvides(MemoryModule.INSTANCE.closeableManager());
  }

  private static final class InstanceHolder {
    private static final MemoryModule_CloseableManagerFactory INSTANCE = new MemoryModule_CloseableManagerFactory();
  }
}
