// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import livekit.org.webrtc.audio.AudioDeviceModule;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_AudioDeviceModuleFactory implements Factory<AudioDeviceModule> {
  private final OverridesModule module;

  public OverridesModule_AudioDeviceModuleFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public AudioDeviceModule get() {
    return audioDeviceModule(module);
  }

  public static OverridesModule_AudioDeviceModuleFactory create(OverridesModule module) {
    return new OverridesModule_AudioDeviceModuleFactory(module);
  }

  @Nullable
  public static AudioDeviceModule audioDeviceModule(OverridesModule instance) {
    return instance.audioDeviceModule();
  }
}
