// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import livekit.org.webrtc.EglBase;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_EglBaseFactory implements Factory<EglBase> {
  private final OverridesModule module;

  public OverridesModule_EglBaseFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public EglBase get() {
    return eglBase(module);
  }

  public static OverridesModule_EglBaseFactory create(OverridesModule module) {
    return new OverridesModule_EglBaseFactory(module);
  }

  @Nullable
  public static EglBase eglBase(OverridesModule instance) {
    return instance.eglBase();
  }
}
