// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import okhttp3.OkHttpClient;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_OkHttpClientFactory implements Factory<OkHttpClient> {
  private final OverridesModule module;

  public OverridesModule_OkHttpClientFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public OkHttpClient get() {
    return okHttpClient(module);
  }

  public static OverridesModule_OkHttpClientFactory create(OverridesModule module) {
    return new OverridesModule_OkHttpClientFactory(module);
  }

  @Nullable
  public static OkHttpClient okHttpClient(OverridesModule instance) {
    return instance.okHttpClient();
  }
}
