// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_DisableCommunicationWorkAroundFactory implements Factory<Boolean> {
  private final OverridesModule module;

  public OverridesModule_DisableCommunicationWorkAroundFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  public Boolean get() {
    return disableCommunicationWorkAround(module);
  }

  public static OverridesModule_DisableCommunicationWorkAroundFactory create(
      OverridesModule module) {
    return new OverridesModule_DisableCommunicationWorkAroundFactory(module);
  }

  public static boolean disableCommunicationWorkAround(OverridesModule instance) {
    return instance.disableCommunicationWorkAround();
  }
}
