// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import livekit.org.webrtc.VideoEncoderFactory;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_VideoEncoderFactoryFactory implements Factory<VideoEncoderFactory> {
  private final OverridesModule module;

  public OverridesModule_VideoEncoderFactoryFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public VideoEncoderFactory get() {
    return videoEncoderFactory(module);
  }

  public static OverridesModule_VideoEncoderFactoryFactory create(OverridesModule module) {
    return new OverridesModule_VideoEncoderFactoryFactory(module);
  }

  @Nullable
  public static VideoEncoderFactory videoEncoderFactory(OverridesModule instance) {
    return instance.videoEncoderFactory();
  }
}
