// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import livekit.org.webrtc.PeerConnectionFactory;
import org.jetbrains.annotations.Nullable;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_PeerConnectionFactoryOptionsFactory implements Factory<PeerConnectionFactory.Options> {
  private final OverridesModule module;

  public OverridesModule_PeerConnectionFactoryOptionsFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public PeerConnectionFactory.Options get() {
    return peerConnectionFactoryOptions(module);
  }

  public static OverridesModule_PeerConnectionFactoryOptionsFactory create(OverridesModule module) {
    return new OverridesModule_PeerConnectionFactoryOptionsFactory(module);
  }

  @Nullable
  public static PeerConnectionFactory.Options peerConnectionFactoryOptions(
      OverridesModule instance) {
    return instance.peerConnectionFactoryOptions();
  }
}
