// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_DisableAudioPrewarmFactory implements Factory<Boolean> {
  private final OverridesModule module;

  public OverridesModule_DisableAudioPrewarmFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  public Boolean get() {
    return disableAudioPrewarm(module);
  }

  public static OverridesModule_DisableAudioPrewarmFactory create(OverridesModule module) {
    return new OverridesModule_DisableAudioPrewarmFactory(module);
  }

  public static boolean disableAudioPrewarm(OverridesModule instance) {
    return instance.disableAudioPrewarm();
  }
}
