// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioHandler;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_AudioHandlerFactory implements Factory<AudioHandler> {
  private final OverridesModule module;

  public OverridesModule_AudioHandlerFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public AudioHandler get() {
    return audioHandler(module);
  }

  public static OverridesModule_AudioHandlerFactory create(OverridesModule module) {
    return new OverridesModule_AudioHandlerFactory(module);
  }

  @Nullable
  public static AudioHandler audioHandler(OverridesModule instance) {
    return instance.audioHandler();
  }
}
