// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import livekit.org.webrtc.VideoDecoderFactory;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_VideoDecoderFactoryFactory implements Factory<VideoDecoderFactory> {
  private final OverridesModule module;

  public OverridesModule_VideoDecoderFactoryFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public VideoDecoderFactory get() {
    return videoDecoderFactory(module);
  }

  public static OverridesModule_VideoDecoderFactoryFactory create(OverridesModule module) {
    return new OverridesModule_VideoDecoderFactoryFactory(module);
  }

  @Nullable
  public static VideoDecoderFactory videoDecoderFactory(OverridesModule instance) {
    return instance.videoDecoderFactory();
  }
}
