// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.AudioType;
import org.jetbrains.annotations.Nullable;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_AudioOutputTypeFactory implements Factory<AudioType> {
  private final OverridesModule module;

  public OverridesModule_AudioOutputTypeFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public AudioType get() {
    return audioOutputType(module);
  }

  public static OverridesModule_AudioOutputTypeFactory create(OverridesModule module) {
    return new OverridesModule_AudioOutputTypeFactory(module);
  }

  @Nullable
  public static AudioType audioOutputType(OverridesModule instance) {
    return instance.audioOutputType();
  }
}
