// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import livekit.org.webrtc.audio.JavaAudioDeviceModule;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_JavaAudioDeviceModuleCustomizerFactory implements Factory<Function1<JavaAudioDeviceModule.Builder, Unit>> {
  private final OverridesModule module;

  public OverridesModule_JavaAudioDeviceModuleCustomizerFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public Function1<JavaAudioDeviceModule.Builder, Unit> get() {
    return javaAudioDeviceModuleCustomizer(module);
  }

  public static OverridesModule_JavaAudioDeviceModuleCustomizerFactory create(
      OverridesModule module) {
    return new OverridesModule_JavaAudioDeviceModuleCustomizerFactory(module);
  }

  @Nullable
  public static Function1<JavaAudioDeviceModule.Builder, Unit> javaAudioDeviceModuleCustomizer(
      OverridesModule instance) {
    return instance.javaAudioDeviceModuleCustomizer();
  }
}
