// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import androidx.annotation.Nullable;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioProcessorOptions;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class OverridesModule_AudioProcessorOptionsFactory implements Factory<AudioProcessorOptions> {
  private final OverridesModule module;

  public OverridesModule_AudioProcessorOptionsFactory(OverridesModule module) {
    this.module = module;
  }

  @Override
  @Nullable
  public AudioProcessorOptions get() {
    return audioProcessorOptions(module);
  }

  public static OverridesModule_AudioProcessorOptionsFactory create(OverridesModule module) {
    return new OverridesModule_AudioProcessorOptionsFactory(module);
  }

  @Nullable
  public static AudioProcessorOptions audioProcessorOptions(OverridesModule instance) {
    return instance.audioProcessorOptions();
  }
}
