// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioRecordSamplesDispatcher;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_LocalAudioSamplesDispatcherFactory implements Factory<AudioRecordSamplesDispatcher> {
  @Override
  public AudioRecordSamplesDispatcher get() {
    return localAudioSamplesDispatcher();
  }

  public static RTCModule_LocalAudioSamplesDispatcherFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static AudioRecordSamplesDispatcher localAudioSamplesDispatcher() {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.localAudioSamplesDispatcher());
  }

  private static final class InstanceHolder {
    private static final RTCModule_LocalAudioSamplesDispatcherFactory INSTANCE = new RTCModule_LocalAudioSamplesDispatcherFactory();
  }
}
