// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.content.Context;
import android.media.AudioAttributes;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioBufferCallbackDispatcher;
import io.livekit.android.audio.AudioRecordSamplesDispatcher;
import io.livekit.android.audio.CommunicationWorkaround;
import io.livekit.android.memory.CloseableManager;
import javax.inject.Provider;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import livekit.org.webrtc.audio.AudioDeviceModule;
import livekit.org.webrtc.audio.JavaAudioDeviceModule;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_AudioModuleFactory implements Factory<AudioDeviceModule> {
  private final Provider<AudioDeviceModule> audioDeviceModuleOverrideProvider;

  private final Provider<Function1<JavaAudioDeviceModule.Builder, Unit>> moduleCustomizerProvider;

  private final Provider<AudioAttributes> audioOutputAttributesProvider;

  private final Provider<Context> appContextProvider;

  private final Provider<CloseableManager> closeableManagerProvider;

  private final Provider<CommunicationWorkaround> communicationWorkaroundProvider;

  private final Provider<AudioRecordSamplesDispatcher> audioRecordSamplesDispatcherProvider;

  private final Provider<AudioBufferCallbackDispatcher> audioBufferCallbackDispatcherProvider;

  public RTCModule_AudioModuleFactory(Provider<AudioDeviceModule> audioDeviceModuleOverrideProvider,
      Provider<Function1<JavaAudioDeviceModule.Builder, Unit>> moduleCustomizerProvider,
      Provider<AudioAttributes> audioOutputAttributesProvider, Provider<Context> appContextProvider,
      Provider<CloseableManager> closeableManagerProvider,
      Provider<CommunicationWorkaround> communicationWorkaroundProvider,
      Provider<AudioRecordSamplesDispatcher> audioRecordSamplesDispatcherProvider,
      Provider<AudioBufferCallbackDispatcher> audioBufferCallbackDispatcherProvider) {
    this.audioDeviceModuleOverrideProvider = audioDeviceModuleOverrideProvider;
    this.moduleCustomizerProvider = moduleCustomizerProvider;
    this.audioOutputAttributesProvider = audioOutputAttributesProvider;
    this.appContextProvider = appContextProvider;
    this.closeableManagerProvider = closeableManagerProvider;
    this.communicationWorkaroundProvider = communicationWorkaroundProvider;
    this.audioRecordSamplesDispatcherProvider = audioRecordSamplesDispatcherProvider;
    this.audioBufferCallbackDispatcherProvider = audioBufferCallbackDispatcherProvider;
  }

  @Override
  public AudioDeviceModule get() {
    return audioModule(audioDeviceModuleOverrideProvider.get(), moduleCustomizerProvider.get(), audioOutputAttributesProvider.get(), appContextProvider.get(), closeableManagerProvider.get(), communicationWorkaroundProvider.get(), audioRecordSamplesDispatcherProvider.get(), audioBufferCallbackDispatcherProvider.get());
  }

  public static RTCModule_AudioModuleFactory create(
      Provider<AudioDeviceModule> audioDeviceModuleOverrideProvider,
      Provider<Function1<JavaAudioDeviceModule.Builder, Unit>> moduleCustomizerProvider,
      Provider<AudioAttributes> audioOutputAttributesProvider, Provider<Context> appContextProvider,
      Provider<CloseableManager> closeableManagerProvider,
      Provider<CommunicationWorkaround> communicationWorkaroundProvider,
      Provider<AudioRecordSamplesDispatcher> audioRecordSamplesDispatcherProvider,
      Provider<AudioBufferCallbackDispatcher> audioBufferCallbackDispatcherProvider) {
    return new RTCModule_AudioModuleFactory(audioDeviceModuleOverrideProvider, moduleCustomizerProvider, audioOutputAttributesProvider, appContextProvider, closeableManagerProvider, communicationWorkaroundProvider, audioRecordSamplesDispatcherProvider, audioBufferCallbackDispatcherProvider);
  }

  public static AudioDeviceModule audioModule(AudioDeviceModule audioDeviceModuleOverride,
      Function1<JavaAudioDeviceModule.Builder, Unit> moduleCustomizer,
      AudioAttributes audioOutputAttributes, Context appContext, CloseableManager closeableManager,
      CommunicationWorkaround communicationWorkaround,
      AudioRecordSamplesDispatcher audioRecordSamplesDispatcher,
      AudioBufferCallbackDispatcher audioBufferCallbackDispatcher) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.audioModule(audioDeviceModuleOverride, moduleCustomizer, audioOutputAttributes, appContext, closeableManager, communicationWorkaround, audioRecordSamplesDispatcher, audioBufferCallbackDispatcher));
  }
}
