// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import kotlin.jvm.functions.Function1;
import livekit.org.webrtc.MediaStreamTrack;
import livekit.org.webrtc.PeerConnectionFactory;
import livekit.org.webrtc.RtpCapabilities;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_SenderCapabilitiesGetterFactory implements Factory<Function1<MediaStreamTrack.MediaType, RtpCapabilities>> {
  private final Provider<PeerConnectionFactory> peerConnectionFactoryProvider;

  public RTCModule_SenderCapabilitiesGetterFactory(
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider) {
    this.peerConnectionFactoryProvider = peerConnectionFactoryProvider;
  }

  @Override
  public Function1<MediaStreamTrack.MediaType, RtpCapabilities> get() {
    return senderCapabilitiesGetter(peerConnectionFactoryProvider.get());
  }

  public static RTCModule_SenderCapabilitiesGetterFactory create(
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider) {
    return new RTCModule_SenderCapabilitiesGetterFactory(peerConnectionFactoryProvider);
  }

  public static Function1<MediaStreamTrack.MediaType, RtpCapabilities> senderCapabilitiesGetter(
      PeerConnectionFactory peerConnectionFactory) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.senderCapabilitiesGetter(peerConnectionFactory));
  }
}
