// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.VideoEncoderFactory;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_VideoEncoderFactoryFactory implements Factory<VideoEncoderFactory> {
  private final Provider<LibWebrtcInitialization> webrtcInitializationProvider;

  private final Provider<Boolean> videoHwAccelProvider;

  private final Provider<EglBase.Context> eglContextProvider;

  private final Provider<VideoEncoderFactory> videoEncoderFactoryOverrideProvider;

  public RTCModule_VideoEncoderFactoryFactory(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<Boolean> videoHwAccelProvider, Provider<EglBase.Context> eglContextProvider,
      Provider<VideoEncoderFactory> videoEncoderFactoryOverrideProvider) {
    this.webrtcInitializationProvider = webrtcInitializationProvider;
    this.videoHwAccelProvider = videoHwAccelProvider;
    this.eglContextProvider = eglContextProvider;
    this.videoEncoderFactoryOverrideProvider = videoEncoderFactoryOverrideProvider;
  }

  @Override
  public VideoEncoderFactory get() {
    return videoEncoderFactory(webrtcInitializationProvider.get(), videoHwAccelProvider.get(), eglContextProvider.get(), videoEncoderFactoryOverrideProvider.get());
  }

  public static RTCModule_VideoEncoderFactoryFactory create(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<Boolean> videoHwAccelProvider, Provider<EglBase.Context> eglContextProvider,
      Provider<VideoEncoderFactory> videoEncoderFactoryOverrideProvider) {
    return new RTCModule_VideoEncoderFactoryFactory(webrtcInitializationProvider, videoHwAccelProvider, eglContextProvider, videoEncoderFactoryOverrideProvider);
  }

  public static VideoEncoderFactory videoEncoderFactory(
      LibWebrtcInitialization webrtcInitialization, boolean videoHwAccel,
      EglBase.Context eglContext, VideoEncoderFactory videoEncoderFactoryOverride) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.videoEncoderFactory(webrtcInitialization, videoHwAccel, eglContext, videoEncoderFactoryOverride));
  }
}
