// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioRecordPrewarmer;
import javax.inject.Provider;
import livekit.org.webrtc.audio.AudioDeviceModule;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_AudioPrewarmerFactory implements Factory<AudioRecordPrewarmer> {
  private final Provider<Boolean> disableAudioPrewarmProvider;

  private final Provider<AudioDeviceModule> audioDeviceModuleProvider;

  public RTCModule_AudioPrewarmerFactory(Provider<Boolean> disableAudioPrewarmProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider) {
    this.disableAudioPrewarmProvider = disableAudioPrewarmProvider;
    this.audioDeviceModuleProvider = audioDeviceModuleProvider;
  }

  @Override
  public AudioRecordPrewarmer get() {
    return audioPrewarmer(disableAudioPrewarmProvider.get(), audioDeviceModuleProvider.get());
  }

  public static RTCModule_AudioPrewarmerFactory create(
      Provider<Boolean> disableAudioPrewarmProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider) {
    return new RTCModule_AudioPrewarmerFactory(disableAudioPrewarmProvider, audioDeviceModuleProvider);
  }

  public static AudioRecordPrewarmer audioPrewarmer(boolean disableAudioPrewarm,
      AudioDeviceModule audioDeviceModule) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.audioPrewarmer(disableAudioPrewarm, audioDeviceModule));
  }
}
