// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.VideoDecoderFactory;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_VideoDecoderFactoryFactory implements Factory<VideoDecoderFactory> {
  private final Provider<LibWebrtcInitialization> webrtcInitializationProvider;

  private final Provider<Boolean> videoHwAccelProvider;

  private final Provider<EglBase.Context> eglContextProvider;

  private final Provider<VideoDecoderFactory> videoDecoderFactoryOverrideProvider;

  public RTCModule_VideoDecoderFactoryFactory(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<Boolean> videoHwAccelProvider, Provider<EglBase.Context> eglContextProvider,
      Provider<VideoDecoderFactory> videoDecoderFactoryOverrideProvider) {
    this.webrtcInitializationProvider = webrtcInitializationProvider;
    this.videoHwAccelProvider = videoHwAccelProvider;
    this.eglContextProvider = eglContextProvider;
    this.videoDecoderFactoryOverrideProvider = videoDecoderFactoryOverrideProvider;
  }

  @Override
  public VideoDecoderFactory get() {
    return videoDecoderFactory(webrtcInitializationProvider.get(), videoHwAccelProvider.get(), eglContextProvider.get(), videoDecoderFactoryOverrideProvider.get());
  }

  public static RTCModule_VideoDecoderFactoryFactory create(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<Boolean> videoHwAccelProvider, Provider<EglBase.Context> eglContextProvider,
      Provider<VideoDecoderFactory> videoDecoderFactoryOverrideProvider) {
    return new RTCModule_VideoDecoderFactoryFactory(webrtcInitializationProvider, videoHwAccelProvider, eglContextProvider, videoDecoderFactoryOverrideProvider);
  }

  public static VideoDecoderFactory videoDecoderFactory(
      LibWebrtcInitialization webrtcInitialization, boolean videoHwAccel,
      EglBase.Context eglContext, VideoDecoderFactory videoDecoderFactoryOverride) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.videoDecoderFactory(webrtcInitialization, videoHwAccel, eglContext, videoDecoderFactoryOverride));
  }
}
