// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_LibWebrtcInitializationFactory implements Factory<LibWebrtcInitialization> {
  private final Provider<Context> appContextProvider;

  public RTCModule_LibWebrtcInitializationFactory(Provider<Context> appContextProvider) {
    this.appContextProvider = appContextProvider;
  }

  @Override
  public LibWebrtcInitialization get() {
    return libWebrtcInitialization(appContextProvider.get());
  }

  public static RTCModule_LibWebrtcInitializationFactory create(
      Provider<Context> appContextProvider) {
    return new RTCModule_LibWebrtcInitializationFactory(appContextProvider);
  }

  public static LibWebrtcInitialization libWebrtcInitialization(Context appContext) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.libWebrtcInitialization(appContext));
  }
}
