// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_VideoHwAccelFactory implements Factory<Boolean> {
  @Override
  public Boolean get() {
    return videoHwAccel();
  }

  public static RTCModule_VideoHwAccelFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static boolean videoHwAccel() {
    return RTCModule.INSTANCE.videoHwAccel();
  }

  private static final class InstanceHolder {
    private static final RTCModule_VideoHwAccelFactory INSTANCE = new RTCModule_VideoHwAccelFactory();
  }
}
