// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_EglContextFactory implements Factory<EglBase.Context> {
  private final Provider<EglBase> eglBaseProvider;

  public RTCModule_EglContextFactory(Provider<EglBase> eglBaseProvider) {
    this.eglBaseProvider = eglBaseProvider;
  }

  @Override
  public EglBase.Context get() {
    return eglContext(eglBaseProvider.get());
  }

  public static RTCModule_EglContextFactory create(Provider<EglBase> eglBaseProvider) {
    return new RTCModule_EglContextFactory(eglBaseProvider);
  }

  public static EglBase.Context eglContext(EglBase eglBase) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.eglContext(eglBase));
  }
}
