// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.memory.CloseableManager;
import io.livekit.android.webrtc.PeerConnectionFactoryManager;
import javax.inject.Provider;
import livekit.org.webrtc.AudioProcessingFactory;
import livekit.org.webrtc.PeerConnectionFactory;
import livekit.org.webrtc.VideoDecoderFactory;
import livekit.org.webrtc.VideoEncoderFactory;
import livekit.org.webrtc.audio.AudioDeviceModule;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_PeerConnectionFactoryManagerFactory implements Factory<PeerConnectionFactoryManager> {
  private final Provider<LibWebrtcInitialization> webrtcInitializationProvider;

  private final Provider<AudioDeviceModule> audioDeviceModuleProvider;

  private final Provider<VideoEncoderFactory> videoEncoderFactoryProvider;

  private final Provider<VideoDecoderFactory> videoDecoderFactoryProvider;

  private final Provider<PeerConnectionFactory.Options> peerConnectionFactoryOptionsProvider;

  private final Provider<CloseableManager> memoryManagerProvider;

  private final Provider<AudioProcessingFactory> audioProcessingFactoryProvider;

  public RTCModule_PeerConnectionFactoryManagerFactory(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider,
      Provider<VideoEncoderFactory> videoEncoderFactoryProvider,
      Provider<VideoDecoderFactory> videoDecoderFactoryProvider,
      Provider<PeerConnectionFactory.Options> peerConnectionFactoryOptionsProvider,
      Provider<CloseableManager> memoryManagerProvider,
      Provider<AudioProcessingFactory> audioProcessingFactoryProvider) {
    this.webrtcInitializationProvider = webrtcInitializationProvider;
    this.audioDeviceModuleProvider = audioDeviceModuleProvider;
    this.videoEncoderFactoryProvider = videoEncoderFactoryProvider;
    this.videoDecoderFactoryProvider = videoDecoderFactoryProvider;
    this.peerConnectionFactoryOptionsProvider = peerConnectionFactoryOptionsProvider;
    this.memoryManagerProvider = memoryManagerProvider;
    this.audioProcessingFactoryProvider = audioProcessingFactoryProvider;
  }

  @Override
  public PeerConnectionFactoryManager get() {
    return peerConnectionFactoryManager(webrtcInitializationProvider.get(), audioDeviceModuleProvider.get(), videoEncoderFactoryProvider.get(), videoDecoderFactoryProvider.get(), peerConnectionFactoryOptionsProvider.get(), memoryManagerProvider.get(), audioProcessingFactoryProvider.get());
  }

  public static RTCModule_PeerConnectionFactoryManagerFactory create(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<AudioDeviceModule> audioDeviceModuleProvider,
      Provider<VideoEncoderFactory> videoEncoderFactoryProvider,
      Provider<VideoDecoderFactory> videoDecoderFactoryProvider,
      Provider<PeerConnectionFactory.Options> peerConnectionFactoryOptionsProvider,
      Provider<CloseableManager> memoryManagerProvider,
      Provider<AudioProcessingFactory> audioProcessingFactoryProvider) {
    return new RTCModule_PeerConnectionFactoryManagerFactory(webrtcInitializationProvider, audioDeviceModuleProvider, videoEncoderFactoryProvider, videoDecoderFactoryProvider, peerConnectionFactoryOptionsProvider, memoryManagerProvider, audioProcessingFactoryProvider);
  }

  public static PeerConnectionFactoryManager peerConnectionFactoryManager(
      LibWebrtcInitialization webrtcInitialization, AudioDeviceModule audioDeviceModule,
      VideoEncoderFactory videoEncoderFactory, VideoDecoderFactory videoDecoderFactory,
      PeerConnectionFactory.Options peerConnectionFactoryOptions, CloseableManager memoryManager,
      AudioProcessingFactory audioProcessingFactory) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.peerConnectionFactoryManager(webrtcInitialization, audioDeviceModule, videoEncoderFactory, videoDecoderFactory, peerConnectionFactoryOptions, memoryManager, audioProcessingFactory));
  }
}
