// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioProcessingController;
import io.livekit.android.webrtc.CustomAudioProcessingFactory;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_AudioProcessingControllerFactory implements Factory<AudioProcessingController> {
  private final Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider;

  public RTCModule_AudioProcessingControllerFactory(
      Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider) {
    this.customAudioProcessingFactoryProvider = customAudioProcessingFactoryProvider;
  }

  @Override
  public AudioProcessingController get() {
    return audioProcessingController(customAudioProcessingFactoryProvider.get());
  }

  public static RTCModule_AudioProcessingControllerFactory create(
      Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider) {
    return new RTCModule_AudioProcessingControllerFactory(customAudioProcessingFactoryProvider);
  }

  public static AudioProcessingController audioProcessingController(
      CustomAudioProcessingFactory customAudioProcessingFactory) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.audioProcessingController(customAudioProcessingFactory));
  }
}
