// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.webrtc.PeerConnectionFactoryManager;
import javax.inject.Provider;
import livekit.org.webrtc.PeerConnectionFactory;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_PeerConnectionFactoryFactory implements Factory<PeerConnectionFactory> {
  private final Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider;

  public RTCModule_PeerConnectionFactoryFactory(
      Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider) {
    this.peerConnectionFactoryManagerProvider = peerConnectionFactoryManagerProvider;
  }

  @Override
  public PeerConnectionFactory get() {
    return peerConnectionFactory(peerConnectionFactoryManagerProvider.get());
  }

  public static RTCModule_PeerConnectionFactoryFactory create(
      Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider) {
    return new RTCModule_PeerConnectionFactoryFactory(peerConnectionFactoryManagerProvider);
  }

  public static PeerConnectionFactory peerConnectionFactory(
      PeerConnectionFactoryManager peerConnectionFactoryManager) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.peerConnectionFactory(peerConnectionFactoryManager));
  }
}
