// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.webrtc.PeerConnectionFactoryManager;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;

@ScopeMetadata("dagger.Reusable")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_RtcThreadTokenFactory implements Factory<RTCThreadToken> {
  private final Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider;

  public RTCModule_RtcThreadTokenFactory(
      Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider) {
    this.peerConnectionFactoryManagerProvider = peerConnectionFactoryManagerProvider;
  }

  @Override
  public RTCThreadToken get() {
    return rtcThreadToken(peerConnectionFactoryManagerProvider.get());
  }

  public static RTCModule_RtcThreadTokenFactory create(
      Provider<PeerConnectionFactoryManager> peerConnectionFactoryManagerProvider) {
    return new RTCModule_RtcThreadTokenFactory(peerConnectionFactoryManagerProvider);
  }

  public static RTCThreadToken rtcThreadToken(
      PeerConnectionFactoryManager peerConnectionFactoryManager) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.rtcThreadToken(peerConnectionFactoryManager));
  }
}
