// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioProcessorOptions;
import io.livekit.android.webrtc.CustomAudioProcessingFactory;
import javax.inject.Provider;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_CustomAudioProcessingFactoryFactory implements Factory<CustomAudioProcessingFactory> {
  private final Provider<LibWebrtcInitialization> webrtcInitializationProvider;

  private final Provider<AudioProcessorOptions> audioProcessorOptionsProvider;

  public RTCModule_CustomAudioProcessingFactoryFactory(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<AudioProcessorOptions> audioProcessorOptionsProvider) {
    this.webrtcInitializationProvider = webrtcInitializationProvider;
    this.audioProcessorOptionsProvider = audioProcessorOptionsProvider;
  }

  @Override
  public CustomAudioProcessingFactory get() {
    return customAudioProcessingFactory(webrtcInitializationProvider.get(), audioProcessorOptionsProvider.get());
  }

  public static RTCModule_CustomAudioProcessingFactoryFactory create(
      Provider<LibWebrtcInitialization> webrtcInitializationProvider,
      Provider<AudioProcessorOptions> audioProcessorOptionsProvider) {
    return new RTCModule_CustomAudioProcessingFactoryFactory(webrtcInitializationProvider, audioProcessorOptionsProvider);
  }

  public static CustomAudioProcessingFactory customAudioProcessingFactory(
      LibWebrtcInitialization webrtcInitialization, AudioProcessorOptions audioProcessorOptions) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.customAudioProcessingFactory(webrtcInitialization, audioProcessorOptions));
  }
}
