// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.e2ee.DataPacketCryptorManager;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_DataPacketCryptorManagerFactoryFactory implements Factory<DataPacketCryptorManager.Factory> {
  @Override
  public DataPacketCryptorManager.Factory get() {
    return dataPacketCryptorManagerFactory();
  }

  public static RTCModule_DataPacketCryptorManagerFactoryFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static DataPacketCryptorManager.Factory dataPacketCryptorManagerFactory() {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.dataPacketCryptorManagerFactory());
  }

  private static final class InstanceHolder {
    private static final RTCModule_DataPacketCryptorManagerFactoryFactory INSTANCE = new RTCModule_DataPacketCryptorManagerFactoryFactory();
  }
}
