// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.memory.CloseableManager;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_EglBaseFactory implements Factory<EglBase> {
  private final Provider<EglBase> eglBaseOverrideProvider;

  private final Provider<CloseableManager> memoryManagerProvider;

  public RTCModule_EglBaseFactory(Provider<EglBase> eglBaseOverrideProvider,
      Provider<CloseableManager> memoryManagerProvider) {
    this.eglBaseOverrideProvider = eglBaseOverrideProvider;
    this.memoryManagerProvider = memoryManagerProvider;
  }

  @Override
  public EglBase get() {
    return eglBase(eglBaseOverrideProvider.get(), memoryManagerProvider.get());
  }

  public static RTCModule_EglBaseFactory create(Provider<EglBase> eglBaseOverrideProvider,
      Provider<CloseableManager> memoryManagerProvider) {
    return new RTCModule_EglBaseFactory(eglBaseOverrideProvider, memoryManagerProvider);
  }

  public static EglBase eglBase(EglBase eglBaseOverride, CloseableManager memoryManager) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.eglBase(eglBaseOverride, memoryManager));
  }
}
