// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.javax.sdp.SdpFactory;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_SdpFactoryFactory implements Factory<SdpFactory> {
  @Override
  public SdpFactory get() {
    return sdpFactory();
  }

  public static RTCModule_SdpFactoryFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static SdpFactory sdpFactory() {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.sdpFactory());
  }

  private static final class InstanceHolder {
    private static final RTCModule_SdpFactoryFactory INSTANCE = new RTCModule_SdpFactoryFactory();
  }
}
