// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioBufferCallbackDispatcher;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_LocalAudioBufferCallbackDispatcherFactory implements Factory<AudioBufferCallbackDispatcher> {
  @Override
  public AudioBufferCallbackDispatcher get() {
    return localAudioBufferCallbackDispatcher();
  }

  public static RTCModule_LocalAudioBufferCallbackDispatcherFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static AudioBufferCallbackDispatcher localAudioBufferCallbackDispatcher() {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.localAudioBufferCallbackDispatcher());
  }

  private static final class InstanceHolder {
    private static final RTCModule_LocalAudioBufferCallbackDispatcherFactory INSTANCE = new RTCModule_LocalAudioBufferCallbackDispatcherFactory();
  }
}
