// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.webrtc.CustomAudioProcessingFactory;
import javax.inject.Provider;
import livekit.org.webrtc.AudioProcessingFactory;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RTCModule_AudioProcessingFactoryFactory implements Factory<AudioProcessingFactory> {
  private final Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider;

  public RTCModule_AudioProcessingFactoryFactory(
      Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider) {
    this.customAudioProcessingFactoryProvider = customAudioProcessingFactoryProvider;
  }

  @Override
  public AudioProcessingFactory get() {
    return audioProcessingFactory(customAudioProcessingFactoryProvider.get());
  }

  public static RTCModule_AudioProcessingFactoryFactory create(
      Provider<CustomAudioProcessingFactory> customAudioProcessingFactoryProvider) {
    return new RTCModule_AudioProcessingFactoryFactory(customAudioProcessingFactoryProvider);
  }

  public static AudioProcessingFactory audioProcessingFactory(
      CustomAudioProcessingFactory customAudioProcessingFactory) {
    return Preconditions.checkNotNullFromProvides(RTCModule.INSTANCE.audioProcessingFactory(customAudioProcessingFactory));
  }
}
