// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import okhttp3.OkHttpClient;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_OkHttpClientFactory implements Factory<OkHttpClient> {
  private final Provider<OkHttpClient> okHttpClientOverrideProvider;

  public WebModule_OkHttpClientFactory(Provider<OkHttpClient> okHttpClientOverrideProvider) {
    this.okHttpClientOverrideProvider = okHttpClientOverrideProvider;
  }

  @Override
  public OkHttpClient get() {
    return okHttpClient(okHttpClientOverrideProvider.get());
  }

  public static WebModule_OkHttpClientFactory create(
      Provider<OkHttpClient> okHttpClientOverrideProvider) {
    return new WebModule_OkHttpClientFactory(okHttpClientOverrideProvider);
  }

  public static OkHttpClient okHttpClient(OkHttpClient okHttpClientOverride) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.okHttpClient(okHttpClientOverride));
  }
}
