// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.content.Context;
import android.net.ConnectivityManager;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_ConnectivityManagerFactory implements Factory<ConnectivityManager> {
  private final Provider<Context> contextProvider;

  public WebModule_ConnectivityManagerFactory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public ConnectivityManager get() {
    return connectivityManager(contextProvider.get());
  }

  public static WebModule_ConnectivityManagerFactory create(Provider<Context> contextProvider) {
    return new WebModule_ConnectivityManagerFactory(contextProvider);
  }

  public static ConnectivityManager connectivityManager(Context context) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.connectivityManager(context));
  }
}
