// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.util.ConnectionWarmer;
import io.livekit.android.room.util.OkHttpConnectionWarmer;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_ConnectionWarmerFactory implements Factory<ConnectionWarmer> {
  private final Provider<OkHttpConnectionWarmer> okHttpConnectionWarmerProvider;

  public WebModule_ConnectionWarmerFactory(
      Provider<OkHttpConnectionWarmer> okHttpConnectionWarmerProvider) {
    this.okHttpConnectionWarmerProvider = okHttpConnectionWarmerProvider;
  }

  @Override
  public ConnectionWarmer get() {
    return connectionWarmer(okHttpConnectionWarmerProvider.get());
  }

  public static WebModule_ConnectionWarmerFactory create(
      Provider<OkHttpConnectionWarmer> okHttpConnectionWarmerProvider) {
    return new WebModule_ConnectionWarmerFactory(okHttpConnectionWarmerProvider);
  }

  public static ConnectionWarmer connectionWarmer(OkHttpConnectionWarmer okHttpConnectionWarmer) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.connectionWarmer(okHttpConnectionWarmer));
  }
}
