// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.net.ConnectivityManager;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.network.NetworkCallbackRegistry;
import javax.inject.Provider;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_NetworkCallbackRegistrarFactory implements Factory<NetworkCallbackRegistry> {
  private final Provider<ConnectivityManager> connectivityManagerProvider;

  public WebModule_NetworkCallbackRegistrarFactory(
      Provider<ConnectivityManager> connectivityManagerProvider) {
    this.connectivityManagerProvider = connectivityManagerProvider;
  }

  @Override
  public NetworkCallbackRegistry get() {
    return networkCallbackRegistrar(connectivityManagerProvider.get());
  }

  public static WebModule_NetworkCallbackRegistrarFactory create(
      Provider<ConnectivityManager> connectivityManagerProvider) {
    return new WebModule_NetworkCallbackRegistrarFactory(connectivityManagerProvider);
  }

  public static NetworkCallbackRegistry networkCallbackRegistrar(
      ConnectivityManager connectivityManager) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.networkCallbackRegistrar(connectivityManager));
  }
}
