// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import javax.inject.Provider;
import okhttp3.OkHttpClient;
import okhttp3.WebSocket;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_WebsocketFactoryFactory implements Factory<WebSocket.Factory> {
  private final Provider<OkHttpClient> okHttpClientProvider;

  public WebModule_WebsocketFactoryFactory(Provider<OkHttpClient> okHttpClientProvider) {
    this.okHttpClientProvider = okHttpClientProvider;
  }

  @Override
  public WebSocket.Factory get() {
    return websocketFactory(okHttpClientProvider.get());
  }

  public static WebModule_WebsocketFactoryFactory create(
      Provider<OkHttpClient> okHttpClientProvider) {
    return new WebModule_WebsocketFactoryFactory(okHttpClientProvider);
  }

  public static WebSocket.Factory websocketFactory(OkHttpClient okHttpClient) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.websocketFactory(okHttpClient));
  }
}
