// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.net.ConnectivityManager;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.memory.CloseableManager;
import io.livekit.android.room.network.NetworkCallbackManager;
import io.livekit.android.room.network.NetworkCallbackRegistry;
import javax.inject.Provider;
import kotlin.jvm.functions.Function1;

@ScopeMetadata("dagger.Reusable")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_NetworkCallbackManagerFactoryFactory implements Factory<Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager>> {
  private final Provider<CloseableManager> closeableManagerProvider;

  private final Provider<NetworkCallbackRegistry> registrarProvider;

  public WebModule_NetworkCallbackManagerFactoryFactory(
      Provider<CloseableManager> closeableManagerProvider,
      Provider<NetworkCallbackRegistry> registrarProvider) {
    this.closeableManagerProvider = closeableManagerProvider;
    this.registrarProvider = registrarProvider;
  }

  @Override
  public Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager> get() {
    return networkCallbackManagerFactory(closeableManagerProvider.get(), registrarProvider.get());
  }

  public static WebModule_NetworkCallbackManagerFactoryFactory create(
      Provider<CloseableManager> closeableManagerProvider,
      Provider<NetworkCallbackRegistry> registrarProvider) {
    return new WebModule_NetworkCallbackManagerFactoryFactory(closeableManagerProvider, registrarProvider);
  }

  public static Function1<ConnectivityManager.NetworkCallback, NetworkCallbackManager> networkCallbackManagerFactory(
      CloseableManager closeableManager, NetworkCallbackRegistry registrar) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.networkCallbackManagerFactory(closeableManager, registrar));
  }
}
