// Generated by Dagger (https://dagger.dev).
package io.livekit.android.dagger;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.stats.NetworkInfo;
import javax.inject.Provider;

@ScopeMetadata("dagger.Reusable")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class WebModule_NetworkInfoFactory implements Factory<NetworkInfo> {
  private final Provider<Context> contextProvider;

  public WebModule_NetworkInfoFactory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public NetworkInfo get() {
    return networkInfo(contextProvider.get());
  }

  public static WebModule_NetworkInfoFactory create(Provider<Context> contextProvider) {
    return new WebModule_NetworkInfoFactory(contextProvider);
  }

  public static NetworkInfo networkInfo(Context context) {
    return Preconditions.checkNotNullFromProvides(WebModule.INSTANCE.networkInfo(context));
  }
}
