// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;
import livekit.org.webrtc.VideoCapturer;
import livekit.org.webrtc.VideoSource;
import livekit.org.webrtc.VideoTrack;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalScreencastVideoTrack_Factory_Impl implements LocalScreencastVideoTrack.Factory {
  private final LocalScreencastVideoTrack_Factory delegateFactory;

  LocalScreencastVideoTrack_Factory_Impl(LocalScreencastVideoTrack_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public LocalScreencastVideoTrack create(VideoCapturer capturer, VideoSource source, String name,
      LocalVideoTrackOptions options, VideoTrack rtcTrack,
      LocalScreencastVideoTrack.MediaProjectionCallback mediaProjectionCallback) {
    return delegateFactory.get(capturer, source, name, options, rtcTrack, mediaProjectionCallback);
  }

  public static Provider<LocalScreencastVideoTrack.Factory> create(
      LocalScreencastVideoTrack_Factory delegateFactory) {
    return InstanceFactory.create(new LocalScreencastVideoTrack_Factory_Impl(delegateFactory));
  }
}
