// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.DefaultsManager;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.PeerConnectionFactory;
import livekit.org.webrtc.VideoCapturer;
import livekit.org.webrtc.VideoSource;
import livekit.org.webrtc.VideoTrack;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalScreencastVideoTrack_Factory {
  private final Provider<PeerConnectionFactory> peerConnectionFactoryProvider;

  private final Provider<Context> contextProvider;

  private final Provider<EglBase> eglBaseProvider;

  private final Provider<DefaultsManager> defaultsManagerProvider;

  private final Provider<LocalVideoTrack.Factory> videoTrackFactoryProvider;

  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  public LocalScreencastVideoTrack_Factory(
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<Context> contextProvider, Provider<EglBase> eglBaseProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<LocalVideoTrack.Factory> videoTrackFactoryProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    this.peerConnectionFactoryProvider = peerConnectionFactoryProvider;
    this.contextProvider = contextProvider;
    this.eglBaseProvider = eglBaseProvider;
    this.defaultsManagerProvider = defaultsManagerProvider;
    this.videoTrackFactoryProvider = videoTrackFactoryProvider;
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
  }

  public LocalScreencastVideoTrack get(VideoCapturer capturer, VideoSource source, String name,
      LocalVideoTrackOptions options, VideoTrack rtcTrack,
      LocalScreencastVideoTrack.MediaProjectionCallback mediaProjectionCallback) {
    return newInstance(capturer, source, name, options, rtcTrack, mediaProjectionCallback, peerConnectionFactoryProvider.get(), contextProvider.get(), eglBaseProvider.get(), defaultsManagerProvider.get(), videoTrackFactoryProvider.get(), rtcThreadTokenProvider.get());
  }

  public static LocalScreencastVideoTrack_Factory create(
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<Context> contextProvider, Provider<EglBase> eglBaseProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<LocalVideoTrack.Factory> videoTrackFactoryProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    return new LocalScreencastVideoTrack_Factory(peerConnectionFactoryProvider, contextProvider, eglBaseProvider, defaultsManagerProvider, videoTrackFactoryProvider, rtcThreadTokenProvider);
  }

  public static LocalScreencastVideoTrack newInstance(VideoCapturer capturer, VideoSource source,
      String name, LocalVideoTrackOptions options, VideoTrack rtcTrack,
      LocalScreencastVideoTrack.MediaProjectionCallback mediaProjectionCallback,
      PeerConnectionFactory peerConnectionFactory, Context context, EglBase eglBase,
      DefaultsManager defaultsManager, LocalVideoTrack.Factory videoTrackFactory,
      RTCThreadToken rtcThreadToken) {
    return new LocalScreencastVideoTrack(capturer, source, name, options, rtcTrack, mediaProjectionCallback, peerConnectionFactory, context, eglBase, defaultsManager, videoTrackFactory, rtcThreadToken);
  }
}
