// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import io.livekit.android.room.track.video.CaptureDispatchObserver;
import javax.inject.Provider;
import livekit.org.webrtc.VideoCapturer;
import livekit.org.webrtc.VideoSource;
import livekit.org.webrtc.VideoTrack;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalVideoTrack_Factory_Impl implements LocalVideoTrack.Factory {
  private final LocalVideoTrack_Factory delegateFactory;

  LocalVideoTrack_Factory_Impl(LocalVideoTrack_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public LocalVideoTrack create(VideoCapturer capturer, VideoSource source, String name,
      LocalVideoTrackOptions options, VideoTrack rtcTrack,
      CaptureDispatchObserver dispatchObserver) {
    return delegateFactory.get(capturer, source, name, options, rtcTrack, dispatchObserver);
  }

  public static Provider<LocalVideoTrack.Factory> create(LocalVideoTrack_Factory delegateFactory) {
    return InstanceFactory.create(new LocalVideoTrack_Factory_Impl(delegateFactory));
  }
}
