// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.audio.AudioBufferCallbackDispatcher;
import io.livekit.android.audio.AudioProcessingController;
import io.livekit.android.audio.AudioRecordPrewarmer;
import io.livekit.android.audio.AudioRecordSamplesDispatcher;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;
import livekit.org.webrtc.AudioTrack;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalAudioTrack_Factory {
  private final Provider<AudioProcessingController> audioProcessingControllerProvider;

  private final Provider<CoroutineDispatcher> dispatcherProvider;

  private final Provider<AudioRecordSamplesDispatcher> audioRecordSamplesDispatcherProvider;

  private final Provider<AudioBufferCallbackDispatcher> audioBufferCallbackDispatcherProvider;

  private final Provider<AudioRecordPrewarmer> audioRecordPrewarmerProvider;

  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  public LocalAudioTrack_Factory(
      Provider<AudioProcessingController> audioProcessingControllerProvider,
      Provider<CoroutineDispatcher> dispatcherProvider,
      Provider<AudioRecordSamplesDispatcher> audioRecordSamplesDispatcherProvider,
      Provider<AudioBufferCallbackDispatcher> audioBufferCallbackDispatcherProvider,
      Provider<AudioRecordPrewarmer> audioRecordPrewarmerProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    this.audioProcessingControllerProvider = audioProcessingControllerProvider;
    this.dispatcherProvider = dispatcherProvider;
    this.audioRecordSamplesDispatcherProvider = audioRecordSamplesDispatcherProvider;
    this.audioBufferCallbackDispatcherProvider = audioBufferCallbackDispatcherProvider;
    this.audioRecordPrewarmerProvider = audioRecordPrewarmerProvider;
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
  }

  public LocalAudioTrack get(String name, AudioTrack mediaTrack, LocalAudioTrackOptions options) {
    return newInstance(name, mediaTrack, options, audioProcessingControllerProvider.get(), dispatcherProvider.get(), audioRecordSamplesDispatcherProvider.get(), audioBufferCallbackDispatcherProvider.get(), audioRecordPrewarmerProvider.get(), rtcThreadTokenProvider.get());
  }

  public static LocalAudioTrack_Factory create(
      Provider<AudioProcessingController> audioProcessingControllerProvider,
      Provider<CoroutineDispatcher> dispatcherProvider,
      Provider<AudioRecordSamplesDispatcher> audioRecordSamplesDispatcherProvider,
      Provider<AudioBufferCallbackDispatcher> audioBufferCallbackDispatcherProvider,
      Provider<AudioRecordPrewarmer> audioRecordPrewarmerProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    return new LocalAudioTrack_Factory(audioProcessingControllerProvider, dispatcherProvider, audioRecordSamplesDispatcherProvider, audioBufferCallbackDispatcherProvider, audioRecordPrewarmerProvider, rtcThreadTokenProvider);
  }

  public static LocalAudioTrack newInstance(String name, AudioTrack mediaTrack,
      LocalAudioTrackOptions options, AudioProcessingController audioProcessingController,
      CoroutineDispatcher dispatcher, AudioRecordSamplesDispatcher audioRecordSamplesDispatcher,
      AudioBufferCallbackDispatcher audioBufferCallbackDispatcher,
      AudioRecordPrewarmer audioRecordPrewarmer, RTCThreadToken rtcThreadToken) {
    return new LocalAudioTrack(name, mediaTrack, options, audioProcessingController, dispatcher, audioRecordSamplesDispatcher, audioBufferCallbackDispatcher, audioRecordPrewarmer, rtcThreadToken);
  }
}
