// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.DefaultsManager;
import io.livekit.android.room.track.video.CaptureDispatchObserver;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.PeerConnectionFactory;
import livekit.org.webrtc.VideoCapturer;
import livekit.org.webrtc.VideoSource;
import livekit.org.webrtc.VideoTrack;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalVideoTrack_Factory {
  private final Provider<PeerConnectionFactory> peerConnectionFactoryProvider;

  private final Provider<Context> contextProvider;

  private final Provider<EglBase> eglBaseProvider;

  private final Provider<DefaultsManager> defaultsManagerProvider;

  private final Provider<LocalVideoTrack.Factory> trackFactoryProvider;

  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  public LocalVideoTrack_Factory(Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<Context> contextProvider, Provider<EglBase> eglBaseProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<LocalVideoTrack.Factory> trackFactoryProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    this.peerConnectionFactoryProvider = peerConnectionFactoryProvider;
    this.contextProvider = contextProvider;
    this.eglBaseProvider = eglBaseProvider;
    this.defaultsManagerProvider = defaultsManagerProvider;
    this.trackFactoryProvider = trackFactoryProvider;
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
  }

  public LocalVideoTrack get(VideoCapturer capturer, VideoSource source, String name,
      LocalVideoTrackOptions options, VideoTrack rtcTrack,
      CaptureDispatchObserver dispatchObserver) {
    return newInstance(capturer, source, name, options, rtcTrack, peerConnectionFactoryProvider.get(), contextProvider.get(), eglBaseProvider.get(), defaultsManagerProvider.get(), trackFactoryProvider.get(), dispatchObserver, rtcThreadTokenProvider.get());
  }

  public static LocalVideoTrack_Factory create(
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<Context> contextProvider, Provider<EglBase> eglBaseProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<LocalVideoTrack.Factory> trackFactoryProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    return new LocalVideoTrack_Factory(peerConnectionFactoryProvider, contextProvider, eglBaseProvider, defaultsManagerProvider, trackFactoryProvider, rtcThreadTokenProvider);
  }

  public static LocalVideoTrack newInstance(VideoCapturer capturer, VideoSource source, String name,
      LocalVideoTrackOptions options, VideoTrack rtcTrack,
      PeerConnectionFactory peerConnectionFactory, Context context, EglBase eglBase,
      DefaultsManager defaultsManager, LocalVideoTrack.Factory trackFactory,
      CaptureDispatchObserver dispatchObserver, RTCThreadToken rtcThreadToken) {
    return new LocalVideoTrack(capturer, source, name, options, rtcTrack, peerConnectionFactory, context, eglBase, defaultsManager, trackFactory, dispatchObserver, rtcThreadToken);
  }
}
