// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;
import livekit.org.webrtc.AudioTrack;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalAudioTrack_Factory_Impl implements LocalAudioTrack.Factory {
  private final LocalAudioTrack_Factory delegateFactory;

  LocalAudioTrack_Factory_Impl(LocalAudioTrack_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public LocalAudioTrack create(String name, AudioTrack mediaTrack,
      LocalAudioTrackOptions options) {
    return delegateFactory.get(name, mediaTrack, options);
  }

  public static Provider<LocalAudioTrack.Factory> create(LocalAudioTrack_Factory delegateFactory) {
    return InstanceFactory.create(new LocalAudioTrack_Factory_Impl(delegateFactory));
  }
}
