// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import livekit.org.webrtc.AudioTrack;
import livekit.org.webrtc.RtpReceiver;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RemoteAudioTrack_Factory {
  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  public RemoteAudioTrack_Factory(Provider<RTCThreadToken> rtcThreadTokenProvider) {
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
  }

  public RemoteAudioTrack get(String name, AudioTrack rtcTrack, RtpReceiver receiver) {
    return newInstance(name, rtcTrack, receiver, rtcThreadTokenProvider.get());
  }

  public static RemoteAudioTrack_Factory create(Provider<RTCThreadToken> rtcThreadTokenProvider) {
    return new RemoteAudioTrack_Factory(rtcThreadTokenProvider);
  }

  public static RemoteAudioTrack newInstance(String name, AudioTrack rtcTrack, RtpReceiver receiver,
      RTCThreadToken rtcThreadToken) {
    return new RemoteAudioTrack(name, rtcTrack, receiver, rtcThreadToken);
  }
}
