// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.webrtc.peerconnection.RTCThreadToken;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;
import livekit.org.webrtc.RtpReceiver;
import livekit.org.webrtc.VideoTrack;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RemoteVideoTrack_Factory {
  private final Provider<CoroutineDispatcher> dispatcherProvider;

  private final Provider<RTCThreadToken> rtcThreadTokenProvider;

  public RemoteVideoTrack_Factory(Provider<CoroutineDispatcher> dispatcherProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    this.dispatcherProvider = dispatcherProvider;
    this.rtcThreadTokenProvider = rtcThreadTokenProvider;
  }

  public RemoteVideoTrack get(String name, VideoTrack rtcTrack, boolean autoManageVideo,
      RtpReceiver receiver) {
    return newInstance(name, rtcTrack, autoManageVideo, dispatcherProvider.get(), receiver, rtcThreadTokenProvider.get());
  }

  public static RemoteVideoTrack_Factory create(Provider<CoroutineDispatcher> dispatcherProvider,
      Provider<RTCThreadToken> rtcThreadTokenProvider) {
    return new RemoteVideoTrack_Factory(dispatcherProvider, rtcThreadTokenProvider);
  }

  public static RemoteVideoTrack newInstance(String name, VideoTrack rtcTrack,
      boolean autoManageVideo, CoroutineDispatcher dispatcher, RtpReceiver receiver,
      RTCThreadToken rtcThreadToken) {
    return new RemoteVideoTrack(name, rtcTrack, autoManageVideo, dispatcher, receiver, rtcThreadToken);
  }
}
