// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;
import livekit.org.webrtc.AudioTrack;
import livekit.org.webrtc.RtpReceiver;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RemoteAudioTrack_Factory_Impl implements RemoteAudioTrack.Factory {
  private final RemoteAudioTrack_Factory delegateFactory;

  RemoteAudioTrack_Factory_Impl(RemoteAudioTrack_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public RemoteAudioTrack create(String name, AudioTrack rtcTrack, RtpReceiver receiver) {
    return delegateFactory.get(name, rtcTrack, receiver);
  }

  public static Provider<RemoteAudioTrack.Factory> create(
      RemoteAudioTrack_Factory delegateFactory) {
    return InstanceFactory.create(new RemoteAudioTrack_Factory_Impl(delegateFactory));
  }
}
