// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.track;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;
import livekit.org.webrtc.RtpReceiver;
import livekit.org.webrtc.VideoTrack;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RemoteVideoTrack_Factory_Impl implements RemoteVideoTrack.Factory {
  private final RemoteVideoTrack_Factory delegateFactory;

  RemoteVideoTrack_Factory_Impl(RemoteVideoTrack_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public RemoteVideoTrack create(String name, VideoTrack rtcTrack, boolean autoManageVideo,
      RtpReceiver receiver) {
    return delegateFactory.get(name, rtcTrack, autoManageVideo, receiver);
  }

  public static Provider<RemoteVideoTrack.Factory> create(
      RemoteVideoTrack_Factory delegateFactory) {
    return InstanceFactory.create(new RemoteVideoTrack_Factory_Impl(delegateFactory));
  }
}
