// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.participant;

import android.content.Context;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.DefaultsManager;
import io.livekit.android.room.RTCEngine;
import io.livekit.android.room.datastream.outgoing.OutgoingDataStreamManager;
import io.livekit.android.room.track.LocalAudioTrack;
import io.livekit.android.room.track.LocalScreencastVideoTrack;
import io.livekit.android.room.track.LocalVideoTrack;
import javax.inject.Provider;
import kotlin.jvm.functions.Function1;
import kotlinx.coroutines.CoroutineDispatcher;
import livekit.org.webrtc.EglBase;
import livekit.org.webrtc.MediaStreamTrack;
import livekit.org.webrtc.PeerConnectionFactory;
import livekit.org.webrtc.RtpCapabilities;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalParticipant_Factory {
  private final Provider<RTCEngine> engineProvider;

  private final Provider<PeerConnectionFactory> peerConnectionFactoryProvider;

  private final Provider<Context> contextProvider;

  private final Provider<EglBase> eglBaseProvider;

  private final Provider<LocalScreencastVideoTrack.Factory> screencastVideoTrackFactoryProvider;

  private final Provider<LocalVideoTrack.Factory> videoTrackFactoryProvider;

  private final Provider<LocalAudioTrack.Factory> audioTrackFactoryProvider;

  private final Provider<DefaultsManager> defaultsManagerProvider;

  private final Provider<CoroutineDispatcher> coroutineDispatcherProvider;

  private final Provider<Function1<MediaStreamTrack.MediaType, RtpCapabilities>> capabilitiesGetterProvider;

  private final Provider<OutgoingDataStreamManager> outgoingDataStreamManagerProvider;

  public LocalParticipant_Factory(Provider<RTCEngine> engineProvider,
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<Context> contextProvider, Provider<EglBase> eglBaseProvider,
      Provider<LocalScreencastVideoTrack.Factory> screencastVideoTrackFactoryProvider,
      Provider<LocalVideoTrack.Factory> videoTrackFactoryProvider,
      Provider<LocalAudioTrack.Factory> audioTrackFactoryProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<CoroutineDispatcher> coroutineDispatcherProvider,
      Provider<Function1<MediaStreamTrack.MediaType, RtpCapabilities>> capabilitiesGetterProvider,
      Provider<OutgoingDataStreamManager> outgoingDataStreamManagerProvider) {
    this.engineProvider = engineProvider;
    this.peerConnectionFactoryProvider = peerConnectionFactoryProvider;
    this.contextProvider = contextProvider;
    this.eglBaseProvider = eglBaseProvider;
    this.screencastVideoTrackFactoryProvider = screencastVideoTrackFactoryProvider;
    this.videoTrackFactoryProvider = videoTrackFactoryProvider;
    this.audioTrackFactoryProvider = audioTrackFactoryProvider;
    this.defaultsManagerProvider = defaultsManagerProvider;
    this.coroutineDispatcherProvider = coroutineDispatcherProvider;
    this.capabilitiesGetterProvider = capabilitiesGetterProvider;
    this.outgoingDataStreamManagerProvider = outgoingDataStreamManagerProvider;
  }

  public LocalParticipant get(boolean dynacast) {
    return newInstance(dynacast, engineProvider.get(), peerConnectionFactoryProvider.get(), contextProvider.get(), eglBaseProvider.get(), screencastVideoTrackFactoryProvider.get(), videoTrackFactoryProvider.get(), audioTrackFactoryProvider.get(), defaultsManagerProvider.get(), coroutineDispatcherProvider.get(), capabilitiesGetterProvider.get(), outgoingDataStreamManagerProvider.get());
  }

  public static LocalParticipant_Factory create(Provider<RTCEngine> engineProvider,
      Provider<PeerConnectionFactory> peerConnectionFactoryProvider,
      Provider<Context> contextProvider, Provider<EglBase> eglBaseProvider,
      Provider<LocalScreencastVideoTrack.Factory> screencastVideoTrackFactoryProvider,
      Provider<LocalVideoTrack.Factory> videoTrackFactoryProvider,
      Provider<LocalAudioTrack.Factory> audioTrackFactoryProvider,
      Provider<DefaultsManager> defaultsManagerProvider,
      Provider<CoroutineDispatcher> coroutineDispatcherProvider,
      Provider<Function1<MediaStreamTrack.MediaType, RtpCapabilities>> capabilitiesGetterProvider,
      Provider<OutgoingDataStreamManager> outgoingDataStreamManagerProvider) {
    return new LocalParticipant_Factory(engineProvider, peerConnectionFactoryProvider, contextProvider, eglBaseProvider, screencastVideoTrackFactoryProvider, videoTrackFactoryProvider, audioTrackFactoryProvider, defaultsManagerProvider, coroutineDispatcherProvider, capabilitiesGetterProvider, outgoingDataStreamManagerProvider);
  }

  public static LocalParticipant newInstance(boolean dynacast, RTCEngine engine,
      PeerConnectionFactory peerConnectionFactory, Context context, EglBase eglBase,
      LocalScreencastVideoTrack.Factory screencastVideoTrackFactory,
      LocalVideoTrack.Factory videoTrackFactory, LocalAudioTrack.Factory audioTrackFactory,
      DefaultsManager defaultsManager, CoroutineDispatcher coroutineDispatcher,
      Function1<MediaStreamTrack.MediaType, RtpCapabilities> capabilitiesGetter,
      OutgoingDataStreamManager outgoingDataStreamManager) {
    return new LocalParticipant(dynacast, engine, peerConnectionFactory, context, eglBase, screencastVideoTrackFactory, videoTrackFactory, audioTrackFactory, defaultsManager, coroutineDispatcher, capabilitiesGetter, outgoingDataStreamManager);
  }
}
