// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.participant;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class LocalParticipant_Factory_Impl implements LocalParticipant.Factory {
  private final LocalParticipant_Factory delegateFactory;

  LocalParticipant_Factory_Impl(LocalParticipant_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public LocalParticipant create(boolean dynacast) {
    return delegateFactory.get(dynacast);
  }

  public static Provider<LocalParticipant.Factory> create(
      LocalParticipant_Factory delegateFactory) {
    return InstanceFactory.create(new LocalParticipant_Factory_Impl(delegateFactory));
  }
}
