// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.participant;

import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;
import io.livekit.android.room.SignalClient;
import io.livekit.android.room.track.RemoteAudioTrack;
import io.livekit.android.room.track.RemoteVideoTrack;
import javax.inject.Provider;
import kotlinx.coroutines.CoroutineDispatcher;
import livekit.LivekitModels;

@ScopeMetadata
@QualifierMetadata("javax.inject.Named")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RemoteParticipant_Factory {
  private final Provider<SignalClient> signalClientProvider;

  private final Provider<CoroutineDispatcher> ioDispatcherProvider;

  private final Provider<CoroutineDispatcher> defaultDispatcherProvider;

  private final Provider<RemoteAudioTrack.Factory> audioTrackFactoryProvider;

  private final Provider<RemoteVideoTrack.Factory> videoTrackFactoryProvider;

  public RemoteParticipant_Factory(Provider<SignalClient> signalClientProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<CoroutineDispatcher> defaultDispatcherProvider,
      Provider<RemoteAudioTrack.Factory> audioTrackFactoryProvider,
      Provider<RemoteVideoTrack.Factory> videoTrackFactoryProvider) {
    this.signalClientProvider = signalClientProvider;
    this.ioDispatcherProvider = ioDispatcherProvider;
    this.defaultDispatcherProvider = defaultDispatcherProvider;
    this.audioTrackFactoryProvider = audioTrackFactoryProvider;
    this.videoTrackFactoryProvider = videoTrackFactoryProvider;
  }

  public RemoteParticipant get(LivekitModels.ParticipantInfo info) {
    return newInstance(info, signalClientProvider.get(), ioDispatcherProvider.get(), defaultDispatcherProvider.get(), audioTrackFactoryProvider.get(), videoTrackFactoryProvider.get());
  }

  public static RemoteParticipant_Factory create(Provider<SignalClient> signalClientProvider,
      Provider<CoroutineDispatcher> ioDispatcherProvider,
      Provider<CoroutineDispatcher> defaultDispatcherProvider,
      Provider<RemoteAudioTrack.Factory> audioTrackFactoryProvider,
      Provider<RemoteVideoTrack.Factory> videoTrackFactoryProvider) {
    return new RemoteParticipant_Factory(signalClientProvider, ioDispatcherProvider, defaultDispatcherProvider, audioTrackFactoryProvider, videoTrackFactoryProvider);
  }

  public static RemoteParticipant newInstance(LivekitModels.ParticipantInfo info,
      SignalClient signalClient, CoroutineDispatcher ioDispatcher,
      CoroutineDispatcher defaultDispatcher, RemoteAudioTrack.Factory audioTrackFactory,
      RemoteVideoTrack.Factory videoTrackFactory) {
    return new RemoteParticipant(info, signalClient, ioDispatcher, defaultDispatcher, audioTrackFactory, videoTrackFactory);
  }
}
