// Generated by Dagger (https://dagger.dev).
package io.livekit.android.room.participant;

import dagger.internal.DaggerGenerated;
import dagger.internal.InstanceFactory;
import javax.inject.Provider;
import livekit.LivekitModels;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RemoteParticipant_Factory_Impl implements RemoteParticipant.Factory {
  private final RemoteParticipant_Factory delegateFactory;

  RemoteParticipant_Factory_Impl(RemoteParticipant_Factory delegateFactory) {
    this.delegateFactory = delegateFactory;
  }

  @Override
  public RemoteParticipant create(LivekitModels.ParticipantInfo info) {
    return delegateFactory.get(info);
  }

  public static Provider<RemoteParticipant.Factory> create(
      RemoteParticipant_Factory delegateFactory) {
    return InstanceFactory.create(new RemoteParticipant_Factory_Impl(delegateFactory));
  }
}
